---
title: "Menggunakan beberapa sumber data"
subtitle: "Pertemuan 10"
author: "Metodologi penelitian"
format: 
  revealjs:
    theme: [simple,../mytheme.scss]
    chalkboard: true
    incremental: false
    transition: convex
    background-transition: fade
    slide-number: true
---

## Mengapa kita menggunakan data?

- Data dapat menyampaikan konteks dengan efisien.
  
    - pembaca orang sibuk. makanya harus efisien.

- Data sangat *powerful* untuk menyampaikan pesan.

- Data menunjukkan seberapa paham kita dengan isu.

- Data biasanya cukup obyektif.

## Bagaimana menggunakan data? {.m}

- data bukanlah cerita! Ia memperkuat.
  - Data adalah support, bukan inti tulisan anda.
  - lebih baik jika sudah ada kerangka berpikir.

- Data tidak harus yang berupa statistik.
  - bisa juga referensi seperti pasal atau argumen orang lain.

- Data harus relevan!
  - jangan pasang data yang anda ga pake.

- Hati-hati dengan informasi yang partisan.

## Beberapa sumber data {.m}

- [World Development Indicators](data.worldbank.org). Memiliki visualisasi yang sangat user friendly dan mudah diakses. Isinya berbagai indikator ekonomi makro dari banyak negara. Dapat diakses dengan package `WDI`.

- [UN COMTRADE database](https://comtrade.un.org/) merupakan sumber data ekspor impor yang dikelola oleh PBB. Memiliki data yang sangat luas tentang ekspor impor berbagai negara dalam berbagai kode HS.

- [BPS](https://www.bps.go.id/) adalah sumber data resmi milik pemerintah. BPS memiliki berbagai data tentang Indonesia yang cukup akurat di bidang ekonomi maupun bidang lainnya.

- [SEKI](https://www.bi.go.id/id/statistik/ekonomi-keuangan/seki/Default.aspx#headingFour) dimaintain BI, isinya indikator-indikator ekonomi termasuk trade. Di BPS juga ada sih.

## WDI {.m}

- Sumber data yang paling enak nyarinya dan sering sekali saya pakai untuk bikin artikel blog.

- dapat mulai dengan mencari indikator ataupun mencari negara.

- Saya biasanya memulai dengan mencari indikator.

- data dapat didisplay, diembed (jika anda cukup tech savvy), dan didwonload dalam bentuk excel.

- Excel akan download semua negara untuk 1 indikator. Jangan lupa difilter.

- Dapat dibuka di [data.worldbank.org](data.worldbank.org)

## WDI in R

- Bagi pengguna R, lebih enak akses WDI pakai package `WDI`.

- Kami menggunakan package `WDI` untuk bikin materi Metopel part 1.

- Untuk menggunakannya, jangan lupa `install.packages("WDI")` lalu `library("WDI")`. Jangan lupa anda perlu internet tiap ngerun WDI.

- Part paling krusial adalam mengetahui "indicator"

## WDI in R

::: panel-tabset


### Kodenya

```r
library(WDI)
library(tidyverse)
library(writexl)

indi<-c(            # membuat dictionary
  "PDB"="NY.GDP.MKTP.CD", ## nama, diikuti indikator di WDI.
  "import"="NE.IMP.GNFS.CD" ## Cek indikator di website.
)

dat<-WDI(           # Menarik data World Bank
  country="all",
  indicator=indi,
  start=2019,end=2019,
)

dat$LPDB<-log(dat$PDB) # menambahkan transformasi log
dat$Limport<-log(dat$import)
write_xlsx(dat,"dat.xlsx") # Ngesave hasilnya dalam excel
View(dat)
```

### WDI di R {.m}

```{r}
library(WDI)
library(tidyverse)
library(writexl)
library(kableExtra)

indi<-c(            # membuat dictionary
  "PDB"="NY.GDP.MKTP.CD", ## nama, diikuti indikator di WDI.
  "import"="NE.IMP.GNFS.CD" ## Cek indikator di website.
)

dat<-WDI(           # Menarik data World Bank
  country="all",
  indicator=indi,
  start=2019,end=2019,
)

dat$LPDB<-log(dat$PDB) # menambahkan transformasi log
dat$Limport<-log(dat$import)
dat %>%
  kbl() %>%
  kable_minimal()
```

### Excelnya

<iframe src="https://onedrive.live.com/embed?cid=ACC929CA35B3A537&resid=ACC929CA35B3A537%21153591&authkey=AM2a0jQRZs_4XIo&em=2" width="800" height="500" frameborder="0" scrolling="no"></iframe>

:::

## UNCOMTRADE

- UN COMTRADE adalah bagian dari PBB yang memiliki fungsi menganalisis perdagangan internasional.

- Database di UN COMTRADE cukup lengkap jika kita tertarik dengan ekspor impor banyak negara dalam HS tertentu.

- Dapat diakses di [comtrade.un.org](https://comtrade.un.org/), lalu pilih "take me to old version" (yg sebelah kanan)

- Hasilnya dapat didownload dalam excel.

## BPS

- Badan Pusat Statistik adalah lembaga resmi milik pemerintah yang bertanggung jawab atas pengumpulan dan diseminasi atas berbagai data.

- Dapat diakses di [bps.go.id](https://www.bps.go.id/)

- Menu yang terpenting ada di kiri, lalu pilih judul tabel yang diinginkan.

- pilih "unduh tabel" di kanan atas, akan didownload dalam excel.

## SEKI

- SEKI dimaintain oleh BI, naturally isinya adalah data-data sektor riil dan keuangan makro seperti exchange rate, interest rate, dan lain sebagainya.

- Data-data trade di SEKI juga lumayan menarik.

- Akses SEKI di [sini](https://www.bi.go.id/id/statistik/ekonomi-keuangan/seki/Default.aspx#headingFour) atau google "SEKI Bank Indonesia"/

- Problem SEKI&BPS->datanya kotor. ga machine readable. Agak PR bersihinnya.

## Penutup

- Anda dapat menggunakan data-data di sini untuk tugas akhir.

- Jangan lupa mensitasi data-data ini jika anda gunakan.

- Tentu saja ada banyak sumber data lain yg dapat anda gunakan. Tapi kalau bisa 4 ini pun sudah lumayan.
