---
title: "Unbundling and the global value chain"
subtitle: "ECES905205 meeting 7"
date: "21 March 2024"
author: "I Made Krisna Gupta"
format: 
  revealjs:
    theme: [simple,../mytheme.scss]
    chalkboard: true
    incremental: false
    transition: convex
    background-transition: fade
    slide-number: true
  beamer: default
---

## So far

- we have discusses extra-industry trade, where countries are buying and selling different goods (e.g., cloth exporter and food exporter)

    - can be driven by difference in technology or factor abundance.

- In industries with significant fixed cost,  we also see that intra-industry trade benefits.

    - gains come from economies of scale, number of brands, and improvement of average productivity.
    
## Today

- Today we discuss the concept of offshoring.

- We also unpack the concept of unbundling stages of production.

## Intro

![feenstra.png]

## Offshoring {.m}

- The provision of a service or the production of various parts of a good in different countries that are then used or assembled into a final good in another location is called **foreign outsourcing**.

    - sometimes called offshoring.
    
- Offshoring is a typoe of international trade that differs from the type we see in Ricardian and H-O models where goods traded are **final goods**.

- Offshoring is trade in _intermediate inputs_, which can sometimes crosses several borders before turned into a final good.

## Offshoring

- At its core, offshoring has the same reasoning as our standard trade model:

    - A firm in a country is better of sourcing part of their production in countries with comparative advantage in that good.
    
- In essence, offshoring breaks down a final good into several intermediate goods (and services).

    - these goods embed different factor intensities.
    
## Unbundling

- To understand offshoring better, we utilise the theory of product unbundling, coined by Richard Baldwin.

- 