# Languages
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
id:
  languageCode: id
  contentDir: content/id
  title: "Krisna 'imed' Gupta"
  params:
    description: "Situs pribadi dari Krisna 'imed' Gupta"
