---
title: "Gains from Asset Trade"
subtitle: "ECES905205 pertemuan 6"
date: "3 Oktober 2024"
date-format: "long"
author: "I Made Krisna Gupta"
format: 
  revealjs:
    theme: [simple,../mytheme.scss]
    chalkboard: true
    incremental: false
    transition: convex
    background-transition: fade
    slide-number: true
  beamer:
    latex-tinytex: true
    latex-auto-install: true
  pptx: default
---

## Intro {.m}

- In this chapter, we see how financially open economies can, in theory, reap gains from financial globalization in the long run.

- We first look at the factors that limit international borrowing and lending, then we look at how a nation’s ability to use international financial markets allows it to accomplish three different goals:

    - Consumption smoothing (by steadying consumption when income fluctuates)
    - Efficient investment (by borrowing to build a productive capital stock)
    - Diversification of risk (by trading of stocks between countries)

## Borrowing constraint

- The ability to borrow in times of need and lend in times of prosperity has profound effects on a country’s well-being.
- Using changes in an economy’s external wealth, we can derive the key constraint that limits its borrowing in the long run: the long-run budget constraint (LRBC). 
- The LRBC tells us precisely how and why a country must, in the long run, “live within its means.”

## Borrowing constraint {.m}

When a household borrows $100,000 at 10% annually, there are two different ways it can deal with its debt each year:

- Case 1 A debt that is serviced. You pay the interest but you never pay any principal.
- Case 2 A debt that is not serviced. You pay neither interest nor principal. Your debt grows by 10% each year.

Case 2 is not sustainable. Sometimes called a rollover scheme, a pyramid scheme, or a Ponzi game, this case illustrates the limits on the use of borrowing. 

In the long run, lenders will not allow the debt to grow larger. This is the essence of the long-run budget constraint.

## Long-run budget constraint {.m}

Here are some assumptions we make in the model economy:

- The country is a small open economy: The country is a price taker and cannot influence prices in world markets for goods and services, nor can it influence the real interest rate.

- It is a real economy: Prices are perfectly flexible. Analysis is in terms of real variables, and we ignore monetary aspects of the economy. There is one real good and one real asset.

- The asset, real debt, carries a real interest rate $r^*$, the world real interest rate, which is constant. The country can lend or borrow an unlimited amount at this interest rate.

## Long-run budget constraint {.m}

- The country pays a real interest rate $r^*$ on its start-of-period debt liabilities L and is also paid r* on its start-of-period debt assets A. Net interest income payments equal to $r^*A − r^*L$, or $r^*W$, where W is external wealth $(A − L)$.

- There are no unilateral transfers (NUT = 0), no capital transfers (KA = 0), and no capital gains on external wealth. Therefore, there are only two nonzero items in the current account: the trade balance TB and net factor income from abroad, $r^*W$.

## Long-run budget constraint {.m}

Change in external wealth from end of $N-1$ to end of $N$ is given by:

$$
\Delta W_N=\underbrace{W_N-W_{N-1}}_{\text{Change in external wealth}}=TB_N+\underbrace{r^*W_{N-1}}_{\text{interest paid/received}}
$$

Wealth at the end of the year thus:

$$
W_N=TB_N+(1+r^*)W_{N-1}
$$

## LR budget constraint {.m}

At the end of year 0: $W_0=(1+r^*)W_1+TB_0$

We assume that all debts owed or owing must be paid off, and the country must end that year with zero external wealth.

At the end of year 1: $W_1=0=(1+r^*)W_0+TB_1$

Cobined: $W_1=0=(1+r^*)^2W_{-1}+(1+r^*)TB_0+TB_1$

2 period budget constraint become:

$$
-(1+r^*)^2W_{-1}=(1+r^*)TB_0+TB_1
$$

## LR budget constraint {.m}

Divide our previous equation with $(1+r^*)$, we get:

$$
\underbrace{-(1+r^*)W_{-1}}_{\text{Minus last period wealth PV}}=\underbrace{TB_0+\frac{TB_1}{(1+r^*)}}_{\text{PV of trade balances}}
$$

The present value of X in period N is the amount that would have to be set aside now so that, with accumulated interest, $X$ is available in $N$ periods. If the interest rate is $r^*$, then the present value of $X$ is $X/(1 + r^*)^N$.

## LRBC {.m}

Let $N$ go to infinity, we get infinite sum and arriveat LRBC:

$$
-(1+r^*)W_{-1}=TB_0+\frac{TB_1}{(1+r^*)}+\frac{TB_2}{(1+r^*)^2}+\cdots
$$
A debtor (creditor) country must have future trade balances that are offsetting and positive (negative) in present value terms.

## Perpetual Loan

Let's compute $PV(X)$ for any stream of constant payment starting in period 1:

$$
\frac{X}{(1+r^*)}+\frac{X}{(1+r^*)^2}+\frac{X}{(1+r^*)^3}+\cdots=\frac{X}{r^*}
$$

For example, the PV of such a stream of payments of a perpetual loan, with $X=100$ and $r^*=0.05$ equals:

$$
\frac{100}{(1+5\%)}+\frac{100}{(1+5\%)^2}+\frac{100}{(1+5\%)^3}+\cdots=\frac{X}{5\%}=2,000
$$

## LRBC

- Since TB=GDP-GNE, LRBC says that _in present value terms, a country's expenditures (GNE) must equal its production (GDP) plus any initial wealth_.

$$

(1+r^*)W_{-1}+GDP_0+\frac{GDP_1}{(1+r^*)}+\frac{GDP_2}{(1+r^*)^2}+\cdots \\
=GNE_0+\frac{GNE_1}{(1+r^*)}+\frac{GNE_2}{(1+r^*)^2}+\cdots

$$

Present value of present and future GNE = present value of country's spending.

## Exorbitant privilege {.m}

The US has been a net debtr with $W=A-L<0$ since the 1980s. Negative external wealth leads to a deficit n net factor income from abroad with $r^*W=r^*(A-L)<0$. Yet as we saw yesterweek, US net factor income from abroad has been positive throughout this period.

- The only way a net debtor can earn a positive net interest income is by receiving a higher rate of interest on its assets than it pays on its liabilities.

- e.g., in the 1960s French officials complained that the US has the "exorbitant privilege" of being able to borrow cheaply while earning higher returns on its foreign investments.

## Manna from Heaven {.m}

- The United States enjoys positive capital gains, KG, on its external wealth. These large capital gains on external assets and the smaller capital losses on external liabilities are gains that cannot be otherwise measured, so their accuracy and meaning is controversial. 

- Some skeptics call these capital gains “statistical manna from heaven.”
- Others think these gains are real and may reflect the United States acting as a kind of “venture capitalist to the world.”
- As with the “exorbitant privilege,” this financial gain for the United States is a loss for the rest of the world. 

## Conclusion {.m}

When we add the +1.5% capital gain differential to the +0.5% interest differential, we end up with a US total return differential (interest+capital gains) of about 2% per year since the 1980s. For comparison, in the same period, the total return differential was close to zero in every other G7 country.

$$
\Delta W_N=W_N-W_{N-1}=TB_N+r^*W_{N-1}+(r^*-r^0)L+KG
$$

## Emerging market

The US borrows low and lends high. For most poorer countries, the opposite is true. They borrow high and lend low. This is because they are riskier borrowers and lenders.

Because of country risk, investors typically demand a risk premium before they will invest in any assets issued by these countries, whether government debt, private equity, private debt, or FDI.

## Consumption smoothing

In this section, we use the long-run budget constraint and a simplified model of an economy to examine the gains from financial globalization.

We focus on the gains that result when an open economy uses external borrowing and lending to eliminate an important kind of risk, namely, undesirable fluctuations in aggregate consumption.

## Consumption smoothing {.m}

We now examine the gains from external borrowing and lending, allowing an economy to eliminate fluctuations in aggregate consumption. We adopt some additional assumptions:
- Real output or GDP (denoted Q) is produced using labor as the only input. Production of GDP may be subject to shocks; depending on the shock, the same amount of labor input may yield different amounts of output.
- We use the terms “household” and “country” interchangeably. Preferences of the country/household are such that it will choose a level of consumption C that is constant over time. This level of smooth consumption must be consistent with the LRBC.

## Consumption smoothing {.m}

- For now, we assume consumption is the only source of demand. Both investment I and government spending G are zero; therefore, GNE equals personal consumption expenditures C.

- Our analysis begins at time 0, and we assume the country begins with zero initial wealth inherited from the past, so that W−1 is equal to zero.

- We assume that the country is small and the rest of the world (ROW) is large, and the prevailing world real interest rate is constant at $r^*$. In the numerical examples that follow, we will assume $r* = 0.05 = 5\%$ per year.

## Consumption smoothing {.m}

These assumptions give us a special case of the LRBC that requires the present value of current and future trade balances to equal zero (amid zero initial wealth):

$$
\underbrace{0}_{\text{initial W}}=\text{PV of TB}=\underbrace{\text{PV of } Q}_{PV \  GDP}-\underbrace{\text{PV of } C}_{PV \ GNE}
$$

## Close vs Open

In a closed economy, TB will always be zero, trhus LRBC will always be satisifed. There won't be any gains from financial globalization.


