---
title: "Agency problem & Insurance"
subtitle: "Week 16"
author: "Krisna Gupta"
date: "7 June 2021 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: monokai
      highlightLines: true
      countIncrementalSlides: false
    css: ["default","dark.css","dark-fonts.css"]

---

## This week

- Agency problem (continued)

- Insurance
  
---

class: middle, center

# Agency problem (continued)

---

## Example 2 of an agency game
.s[
- Let a principal needs to repair its code to run faster. An upgraded version would benefit the principal Rp1 billion. The old version doesn't change the principal's profit.

- The principal hire an agent who is an expert in this field. A contract is drafted to hire such agent.

- The worker has two options: work hard will cost the agent Rp30 million, while work lazy will cost 0. This action is invisible to the principal.

- High effort leads to $\frac{2}{3}$ probability of useful product, while low effort has only $\frac{1}{3}$ probability of producing good product.

- good product will fix the code (hence benefit the principal Rp1 billion), while the bad product is worthless for the principal.

- The agent can accept this contract or other contract which will give the agent Rp100 million without extra export.
]

---

## Example 2

- The principal needs to design a contract such that maximise its benefit regardless of the agent's behavior.
  + This is mainly because the agent's behavior is unobservable
  
- The principal's problem: 
  1. high salary contract can provide incentive to agent to work hard, but leads to low benefit for the principal.
  1. low salary contract benefits principal, but may not motivate agent to work hard.
  
- However, the principal can offer a contract based on the product: high salary for good product, low salary for bad product.
  + but how high is high? How low is low?
  
---

## Solving Example 2

- The principal problem is to maximize benefit minus salary $s$.

$$\max_s 10^9-s$$

- The agent will take the contract if and only if:

$$s-e(30 \times 10^6)\geq100\times 10^6$$

where $e=1$ for high effort, and $e=0$ for low effort.

- Now we have a problem: outcome for the principal is not always 1 billion.

---

## Example 2: case with certainty

- Let's consider first the case where the agent will always give good product when $e=1$, and always give bad product when $e=0$.

- In this case, it is obvious that the principal would want the agent to work hard, which means effort must always be = 1.

- The principal should offer a contract where salary is high when agent give high effort, but salary is low when agent give low effort.

- The salary of high-effort must be high enough so the agent accept the contract.

---

## Example 2: case with certainty

The principal should offer s that satisfy this condition:

$$s-30 \times 10^6=100\times 10^6$$

Rearrange to get:

$$s=130\times 10^6$$

That is, the agent will accept and work hard as long as the payment is higher than his/her opportunity cost.

With that salary, the principal will get profit:

$$profit=10^9-130\times 10^6$$

Hence, the contract should offer a set of two salaries: a slightly higher than 130million for good product and zero otherwise.

---

## Example 2: case with uncertainty

- With uncertainty, however, the payoff received by both is a gamble.

- Since the agent's action is still unobservable, the principal still offer a contract which makes agent indifferent between accepting and rejecting, but also between low effort and high effort.

- Let $s_1$ be the payment when the product is good and $s_0$ be the payment when the product is bad.

---

## Example 2: case with uncertainty

- the agent will accept the contract AND put high effort when:

$$\left(\frac{2}{3}\times s_1+ \frac{1}{3} \times s_0 \right)-30=100$$

- the agent will accept the contract AND put low effort when:

$$\frac{1}{3}\times s_1+ \frac{2}{3} \times s_0=100$$

Now we have a system with 2 equations and 2 unknowns, which can be solved with a simple algebra.

it'll give us the LEAST possible payment to offer. Less than this combination and agent will reject the contract. More will make principal's payoff lower.

---

## Example 2: case with uncertainty

- With that combination of payoff, the agent will be indifferent between putting low effort and high effort.

- The principal payoff when the agent work hard:
 
$$\frac{2}{3} \times (1B-s_1) + \frac{1}{3} \times (0-s_2)$$

- The principal payoff when the agent is lazy:
 
$$\frac{1}{3} \times (1B-s_1) + \frac{2}{3} \times (0-s_2)$$

- To nudge the agent toward high effort, 

---

class: middle, center

# Role of Insurance

---

## Uncertainty

- A lot of people does not like uncertainty.

- To some extent, uncertainty can be mitigated by insurance.

- We know many consumer insurance:
  + Wealth-related: car, motorcycle, house.
  + Health-related: BPJS, life insurance, etc.
  
- There are also producer insurance:
  + LPS (bank insurance), harvest insurance, cargo insurance.
  
- But how does insurance work?

---

## Insurance

- Insurance works by **pooling risk**.

- Consider a neighborhood where:

  + 1000 car owners
  + 10% chance in a car will be stolen.
  + All cars in this neighborhood value Rp300 Million.
  
- For each person, they face a 10% probability of a loss of Rp300 million.

- As a neighborhood, however, this becomes a certainty:
  + out of 1000 cars, 100 of them will be stolen.
  + We just don't know who's car is going to be stolen.
  
---

## Insurance

- This is when the insurance comes in.

- Let's introduce an insurance scheme where:
  + a brand new car will be replaced for anyone who lost their car.
  + Every car owners pay Rp 30 Million annually
  
- Each car owners then face this option:
  + Not getting the insurance, their wealth is Rp300 million with 10% probability it reduces to zero (stolen), or
  + Take the insurance, their wealth is a certain Rp270 million (a stolen car will be replaced with a car with same price).
  
- Will you take the insurance?

---

## Certainty equivalent

- The two options are actually very similar.

- We have seen before in the investment scheme, a concept called **certainty equivalent**.

- Every gamble has a certainty equivalent EV:

$$EV=\sum_i \pi_i \times V_i$$

- In our case, the certainty equivalent of the car without insurance is:

\begin{align}
EV &= 0.9 \times 300 + 0.1 \times 0 \\
EV &= 270
\end{align}

---

## Risk aversion

- Paying the insurance will lead to a certain Rp270 million, which is exactly equals to EV.

- A person is said to have a **risk-neutral preference** when they are indifference between a certainty and a gamble with the same EV.

- In our case, a risk neutral person will be indifferent between taking the insurance and accept the gamble.

- A person with **risk-loving preference** will opt for the gamble, while a person with **risk-averse preference** will take the insurance.

---

## Insurance margin

- Most people and businesses are risk-averse.

- In fact, risk-aversion is where the insurance companies get their margin.

- Let's get back to our neighborhood. Suppose all 1000 people buys the insurance priced Rp30 million.

- If there's only one insurance company, then the company's revenue:

\begin{align}
R &= 30\times 1000
R &= 30,000
\end{align}

or Rp30 Billion in revenue. What about the cost?

---

## Insurance margin

- There will be 100 cars needed to be bought by the company to replace stolen cars.

- This means the cost is:

\begin{align}
C &= 100 \times 300
C &= 30,000
\end{align}

Also Rp30 Billion

---

## Insurance margin

- If all of the people in the neighborhood are risk-neutral, they won't buy insurance higher than Rp30 million.

- This means, there will be no margin for the insurance company.

- The fact that we have insurance companies operate today suggests risk-aversion in the general population.

- Suppose the neighborhood filled with risk-averse people who buy insurance at Rp40 million $\Rightarrow$ Revenue is 40 billion, a 10 billion profit.

- The cost is the same, but revenue of the company is higher.

---

## Problem with insurance

There are generally two problems with insurance:

- **Moral Hazard** is a situation where people's action changes after they are covered by insurance.

- Some people behave recklessly when they know they are covered by an insurance which changes their risk profile.

- In our example with 10% chance of stolen car, a covered person may behave more recklessly, like not locking their car. These reckless behavior increases chance their car get stolen, which rise insurance company's cost.

- One example is banks: A bank that knows they will receive bail-out when they fail may lend recklessly or buys a risky asset. Same goes with State-Owned Enterprise.

---

## Problem with insurance

- **Adverse Selection** occurs when people have different risk profile. This makes pricing the insurance premium tricky.

- Consider a health insurance in a city where 10% of its people will get lung cancer.

- Risk profile differes among people. A non-smoker may have less than 10% chance of getting a lung cancer, whereas a smoker may have much higher chance.

- If there's a risk-neutral insurance price, a healthy person may risk getting the lung cancer since his/her risk is much lower.

- If healthy people opt-out, the risk premium must increase because only high risk profile will buy the insurence: the aggregate chance will be higher than 10%

---

## Adverse selection

- One way to avoid adverse selection is to make a insurance an obligation.

- In Australia, all car must have insurance to cover road accident. Health insurance also a must for everyone, including foreigner.

- By making insurance a mandatory, even healthy people will have to buy the insurance, hence making the risk profile of the insurance closer to country average.

- BPJS also behave like this, which is good!

---

## The end of the course

- Feel free to ask question.

- The final will be up to this point.

- I bid you good luck