---
title: "Ujian Akhir Semester"
subtitle: "ECES905205 \n Analisis Ekonomi Perdagangan dan Industri"
author: "I Made Krisna Yudhana Wisnu Gupta"
date: "12 Desember 2022"
format:
  pdf:
    documentclass: scrartcl
    papersize: a4paper

---

```{=tex}
\begin{center}
\rule{5.9in}{0.5pt}
\end{center}
```
# Instruksi Ujian

1. Waktu ujian adalah **3 jam** (60x3 menit).
1. close book, no electronics kecuuali kalkulator (**kalkulator diperbolehkan**), boleh bawa max **5 lembar A4** bolak-balik (dikumpulkan bersama kertas jawaban).
1. Jumlah soal ada 4. Kerjakan yang dianggap paling mudah dahulu.
1. Angka di sebelah soal yang ada di dalam kurung adalah total available poin untuk soal tersebut. Total bobot adalah 100.
1. Usahakan menjawab soal dengan jumlah kata seefisien mungkin. Nulis kebanyakan tidak akan menambah angka (ongkos nulis = 0).
1. 4 soal tersebut dapat dikerjakan acak, tapi mohon per nomor-nya konsisten (misalnya jika kerjakan nomer 4 duluan boleh tapi mohon selesaikan semuua pertanyaan di nomor 4 dulu sebelum pindah ke nomor lain.)
1. Jika ada soal yang memerlukan analisis dengan grafik, tidak perlu terlalu presisi tidak apa-apa.
1. Jika sudah bingung tidak tahu mau pakai tools mana, silakan mencoba kasih penjelasan verbal yang logis daripada dikosongin.
1. Selamat mengerjakan dan semoga sukses.

# Soal

## Pertanyaan 1: Hecksher-Ohlin Economy (25)

Negara Sokovia dengan karakteristik Hecksher-Ohlin economy memiliki 2 industri F dan C dengan teknologi sebagai berikut:
```{=tex}
\begin{align*}
F=K^{\alpha}L^{\beta} \\
C=K^{\gamma}L^{\delta}
\end{align*}
```

di mana $\alpha+\beta=1$ dan $\gamma+\delta=1$. $K$ (kapital) dan $L$ (pekerja) adalah faktor produksi yang bergerak bebas antar industri. Total $K$ yang dapat digunakan oleh F dan C adalah $\bar{K}$, dan total $L$ yang dapat digunakan oleh kedua industri adalah $\bar{L}$. Dengan kata lain:
```{=tex}
\begin{align*}
K_F+K_C&=\bar{K} \\
L_F+L_C&=\bar{L}
\end{align*}
```
harga yang harus dibayar oleh pengguna $K$ adalah, $r$, dan harga yang harus dibayar pengguna $L$ adalah $w$

a. Agar F dapat disebut capital-intensive relative to C, apa restriksi yang harus diberikan kepada parameter $\alpha, \beta, \gamma \ \text{dan} \ \delta$? (3)

b. Kenapa kita bisa mendapatkan nilai optimal dari factor demand dengan cara melakukan $MRS=\frac{w}{r}$? (4)

Gunakan angka-angka berikut ini sebagai parameter di negara Sokovia untuk menjawab (c) dan (d):

$$
\alpha = \frac{1}{4}, \ 
\beta = \frac{3}{4}, \
\gamma = \frac{1}{3},\
\delta = \frac{2}{3}
$$

c. Cari factor input demand untuk kedua industri tersebut sebagai fungsi dari $w,r,\bar{K} \ \text{dan} \ \bar{L}$ ! (10)

d. Tiba-tiba negara Sokovia menerbitkan sebuah peraturan baru yaitu Omnibus Law yang mengakibatkan investasi asing berbondong-bondong masuk ke Sokovia. Akibatnya $\bar{K}$ naik jadi $\hat{K}$ di mana $\hat{K}>\bar{K}$. Omnibus Law ini tidak mengatur pekerja sehingga $L$ tidak berubah. Apa yang terjadi pada demand kapital dan tenaga kerja di kedua industri tersebut? Gunakan jawaban anda di (c) untuk menganalisis dampak Omnibus Law di Sokovia! (8)


## Pertanyaan 2: Balance of Payment (25)

a. Jelaskan apa yang dimaksud dengan paham merkantilisme! Jelaskan mekanisme yang membuat merkantilisme menjadi paham yang tidak lagi relevan. Hint: ingat kembali why we export? (5)

b. Neraca pembayaran selalu surplus! Apabila terjadi surplus neraca perdagangan, maka apa yang, secara aritmatik (secara akuntansi) yang akan menyeimbangkannya? Jelaskan setiap kemungkinan yang ada! (5)

c. Apakah naiknyua interest rate Amerika Serikat dapat berdampak ke performa ekspor impor Indonesia? Jelaskan mekanismenya! (5)

d. Jelaskan apa yang dimaksud dengan "exorbitant privilige". Bagaimana hal tersebut mempengaruhi perdagangan internasional? (5)

5. Jelaskan kenapa mendorong ekspor dan menekan impor tanpa meningkatkan produktivitas ekonomi malah berpengaruh negatif terhadap kesejahteraan! (5)

## Pertanyaan 3: The New Industrial Policy (25)

a. Apa bedanya kebijakan industrial baru dan yang lama? Elaborasikan dengan lengkap jawaban anda (5)

b. Tentang Cherif dan Hasanov (2019):

    i. Mengapa dikatakan bahwa industrial policy hanya valid untuk industri yang baru (emerging)! (5)

    ii. Apa yang dimaksud dengan government failure? Berikan 2 contoh! (5)

c. Kebijakan industri dan perdagangan adalah soal keberpihakan. Jelaskan maksud dari statement tersebut! (2)

d. Dari kebijakan-kebijakan berikut ini, jelaskan siapa yang diuntungkan dan siapa yang dirugikan (8):

    - Tarif impor
    
    - Subsidi ekspor
    
    - kuota impor
    
    - Voluntary Export Restriction
    


## Pertanyaan 4: Industrial Policy in Practice (25)

a. Seandainya ada tiga kebijakan yang dilakukan sebuah pemerintahan::

    - subsidi produksi biodiesel..
    
    - larangan ekspor bahan baku nikel untuk industri baterai sel.
    
    - Tariff anti-dumping impor industri baja

Justrifikasi ekonomi apa yang dapat diberikan untuk kebijakan-kebijakan tersebut dari sudut pandang efisiensi ekonomi? Apa market failure yang coba diaddress? (9)

b. Apa itu infant industry? Di Indonesia, apakah istilah infant industry dapat disematkan pada industri biodiesel, baterai sel dan industri baja? Mana yang bisa dan mana yang tidak bisa? Jelaskan jawaban anda! (8)

c. Jelaskan apa saja **cost** dari 3 kebijakan di atas. SIapakah yang menanggung cost tersebut? (8)
    
---------------------------------

# Jawaban

## Pertanyaan 1

a. Agar F disebut capital-intensive, maka harus hold: $\frac{\alpha}{\beta} > \frac{\gamma}{\delta}$

b. Couple of ways to answer this, more or less mirip, dan yg manapun cara anda jawab, akan dapat full score: 

    - Karena $\alpha+\beta = \gamma+\delta = 1$ yang artinya F dan C adalah fungsi yang convex dan monotonic. Resource constraint untuk $K$ dan $L$ juga convex, sehingga kita dapat menggunakan metode lagrange untuk mendapatkan titik maksimal untuk F dan C. 

    - Karena ketika MRS $=\frac{w}{r}$ adalah titik persinggungan alokasi kapital dan labour yang memaksimalkan jumlah F dan C yang dihasilkan given resource constraint.
    
c. Dengan parameter yang didapat dari soal, kita akan punya:

```{=tex}
\begin{align*}
F&=K^{1/4}L^{3/4} \\
C&=K^{1/3}L^{2/3} \\
subject \ to: \ &K_F+K_C = \bar{K} \\
&L_F+L_C=\bar{L}
\end{align*}
```


Kita set MRS=$\frac{w}{r}$ untuk F dan C, kita akan dapat:

$$
\frac{L_F}{K_F}=3\frac{r}{w}
$$

$$
\frac{L_C}{K_C}=2\frac{r}{w}
$$

ada banyak cara untuk approach ini. Ini hanya salah satunya. Ubah 2 persamaan di atas jadi:

$$
L_F=3\frac{r}{w}K_F
$$

$$
L_C=\frac{r}{w} 2K_C
$$

Substitusi ke constraint labour $L_F+L_C=\bar{L}$

$$
3\frac{r}{w}K_F+2\frac{r}{w}K_C=\bar{L}
$$

kali dua sisi dengan $\frac{w}{r}$

$$
3K_F+2K_C=\frac{w}{r}\bar{L}
$$

Substitusi atau eliminasi dengan constraint kapital $K_F+K_C=\bar{K}$ akan didapat dua K:

$$
K_F^*=\frac{w}{r}\bar{L}-2\bar{K}
$$

$$
K_C^*=3\bar{K}-\frac{w}{r}\bar{L}
$$

Substitusi lagi either ke MRS=w/r atau ke labour constraint:

$$
L^*_C=6\frac{r}{w}\bar{K}-2\bar{L}
$$

$$
L_F^*=3\bar{L}-6\frac{r}{w}\bar{K}
$$

Tentu saja di jawaban anda, anda harus sampaikan step-by-stepnya mulai dari MRS=w/r sampai ketemu labour and capital demand.

d. Dari empat persamaan di atas, kita bisa analisis apa yang terjadi ketika ada economic reform yang membuat kapital meningkat. Dari lihat tandanya saja, kita bisa tau bahwa jika kapital naik, maka $K_C^*$ dan $L_C^*$ akan naik, sementara $K_F^*$ dan $L_F^*$ akan turun. Kita bisa lihat bahwa naiknya kapital akan meningkatkan kapital dan labour demand (dan otomatis produksi) bagi sektor C yang dalam hal ini  relatively more capital-intensive. 

Dengan kata lain, naiknya investasi menyebabkan bias growth ke industri yang relatively capital-intensive.

Tentunya anda juga bisa lakukan partial derivative:

$$
\frac{\partial K_C}{\partial \bar{K}}= 3 > 0
$$
$$
\frac{\partial K_F}{\partial \bar{K}}= -2 < 0
$$
$$
\frac{\partial L_C}{\partial \bar{K}}= 6\frac{r}{w} > 0
$$
$$
\frac{\partial L_F}{\partial \bar{K}}= -6\frac{r}{w} < 0
$$

Tapi ga partial derivative gpp asalkan jawabannya bener dan reasoningnya masuk.

## Pertanyaan 2

a. Paham merkantilisme adalah paham yang percaya bahwa suatu negara harus mendorong ekspor dan membatasi impor. Paham ini dulu muncul karena negara ingin mengumpulkan cadangan devisa berupa emas. Saat ini paham tersebut tidak lagi relevan karena ekonom sudah memahami comparative advantage dan diminishing return (i.e., semakin banyak emas, maka harga emas akan turun -> emas tidak lagi berharga -> inflasi). Sama juga dengan mata uang di mana mata uang akan menguat dan mendorong berkurangnya insentif untuk ekspor dan meningkatnya insentif untuk impor.

b. Dari sisi BoP (neraca pembayaran), neraca perdagangan yang surplus akan diseimbangkan oleh neraca finansial (financial account) yang negatif. Beberapa komponen BoP yang menyeimbangkannya antara lain:

    - uang hasil ekspor yang diparkir di luar negeri, dihitung sebagai outward investment, atau pembelian aset perbankan asing oleh eksportir.
    
    - uang hasil ekspor ditukar rupiah yang tidak digunakan, hal ini akan diseimbangkan dengan penguatan nilai rupiah.
    
    - uang hasil ekspor ditukar rupiah, yang dijual oleh BI, BI menggunakan dolarnya untuk membeli aset asing untuk menyeimbangkan BoP tanpa mempengaruhi nilai tukar.
    
Bagi yang menjawab dalam konteks $Y=C+I+G+(NX)$ akan tetap diberi partial credit, but note bahwa penjelasan lewat $Y=C+I+G+(NX)$ adalah penjelasan untuk poin e.

c. interest rate AS naik $\rightarrow$ membeli aset AS jadi lebih menarik $\rightarrow$ investor pada beli USD $\rightarrow$ USD terapresiasi terhadap mata uang lain termausk IDR $\rightarrow$ harga barang ekspor Indonesia turun, harga barang impor naik (ToT turun) karena XR effect $\rightarrow$ demand internasional naik $\rightarrow$ ekspor naik, impor turun.

d. exorbitant privilege adalah keistimewaan yang dimiliki AS (tepatnya sentral bank AS) karena mata uangnya dijadikan _reserve currency_ (cadev) oleh bank sentral negara-negara lain. Karena USD digunakan sebagai cadev negara lain, maka aset AS, dijual berapapun, akan tetap laris. Hal ini membuat AS dapat menerbitkan surat utang terus dan menjaga defisit neraca perdagangan dalam waktu yang sangat lama, tanpa mengalami penurunan nilai tukar yang signifikan. Akibatnya, secara global defisit AS harus diimbangi dengan surplus dari negara lain yang menggunakan ekspornya untuk membayari defisit AS tersebut. 

e. Kita dapat gunakan persamaan agregat demand (AD) $Y=C+I+G+(NX)$ :

    - pertumbuhan ekonomi secara fundamental adalah lewat akumulasi faktor produksi dan teknologi. ie, Y=F(K,L,A). jika faktor produksi dan teknologi tidak berubah, maka suplai barang dan jasa akan fix ($Y=\bar{Y}$).
    
    - Jika NX ditingkatkan dalam kondisi di mana $Y=\bar{Y}$, maka sisi kanan dari persamaan AD harus mengurangi variabel yang lain, antara C,I,G, atau kombinasi dari ketiganya.
    
    - Dengan kata lain, kita bisa meningkatkan ekspor dengan mengurangi konsumsi dan investasi dalam negeri. Tentunya hal ini akan berakibat negatif pada kesejahteraan Indonesia karena kesejahteraan diukur dari jumlah konsumsi penduduk Indonesia, baik konsumsi produk domestik maupun produk impor.
    
## Pertanyaan 3

a. lihat slide pertemuan 10 halaman 6

b1. Industrial policy sebaiknya digunakan untuk mengatasi market failure, di mana market failure ini mencegah sebuah industri untuk muncul _in the first place_. Industri baru ini, ketika hambatannya dapat diatasi, akan memberikan dampak yang signifikan dan sanggup menutup cost yang dikeluarkan di awal. Market failure ini umumnya adalah economies of scale (network effect, coordination problem), learning externalities (endogeneous growth/learning), dan imperfect capital market.

b2. Government failure adalah sebuah kegagalan yang dialami oleh sistem distribusi sumber daya (faktor produksi serta barang dan jasa) yang dilakukan oleh pemerintah, yang mengakibatkan pola distribusi yang tidak optimal bahkan ketika dibandingkan dengan sistem pasar. Beberapa contohnya adalah mainly terkait korupsi, inkompetensi.

c. kebijakan yang memiliki dampak positif pada 1 industri biasanya memiliki dampak buruk ke industri lain baik langsung maupun tidak langsung.

d. untung dan buntung:

d1. **Tarif impor**. untung: produsen domestik, pendapatan pemerintah. Buntung: konsumen (baik produk akhir maupun industri hilir).

d2. **Subsidi ekspor**. untung: eksportir produk yang dituju, penduduk negara tujuan ekspor. Buntung: konsumen domestik (termasuk industri hilir pengguna), pendapatan pemerintah.

d3. **kuota impor**. untung: produsen domestik, importir. Buntung: konsumen (baik produk akhir maupun industri hilir).

d4. **VER**. untung: produsen asing di negara eksportir, produsen domestik. Buntung: konsumen.

## Pertanyaan 4

a1. **subsidi biodiesel**. infant industry argument: ketika scale sudah besar dan knowhow sudah terkumpul, bisa run sendiri tanpa perlu disubsidi.

a2. **