---
title: "Trade policies for development"
subtitle: "ECES905205 pertemuan 9"
date: "10 Oktober 2022"
author: "I Made Krisna Gupta"
format: 
  revealjs:
    theme: [simple,../mytheme.scss]
    chalkboard: true
    incremental: false
    transition: convex
    background-transition: fade
    slide-number: true
  beamer: default
---

## Last Week {.m}

- Argument pro-trade
    
    - Static efficiency: specialisation, economies of scale, productivity selection.
    
    - Dynamic efficiency: learning-by-exporting.
    
- Argument against free trade:

    - Zero-sum-game for large countries (leads to FTAs)
    
    - Zero-sum-game for losers (usually better organized)
    
    - Market failures: externalities, infant industry.
    
- For any justified government intervention, domestic policies should perform better than trade policies.

## Trade policies for development

- In the government's eyes, trade policies often serves as a policy development.

- While we have discussed that usually domestic policies are better, free-ish trade is not the norm.

    - Free trade only really took off after World War 2.
    
- Today, we discusses trade policies for development usually used by developing countries.

## Import Substitution Strategy

- Based on infant industry argument:

    - need time to compete with the global market.
    
    - requires a short term protection (usually tariff & quota)

- was popular among developing countries pre-1970s (Asian Tigers included), but also developed countries pre-WW2.

- Infant industry argument is really powerful among policy makers.

## Infant industry problem {.m}

- Protection against a good that the country is not comparatively good at will only resulted in higher cost.

    - protection against capital intensive goods in a country with no capital, protection against goods reuires a certain climate.
    
- India & Pakistan protects heavy-manufacturing goods (e.g., cars & steel), but they ended up exporting light-manufacturing goods (e.g., textiles).

- needs to ensure that those industry exports **because** of the past protection.

- Needs to **separate** real infant industry that will grop up in the future with the forever infant (rent seeker)

## Infant industry justification

- If an industri is truly infant, the capital market should have no problem with providing liquidity.

    - Often happens: funds flow to potential industries.
    
- However, capital market in developing countries does not function as good as developed countries'

    - Bank is not efficient, interest rate is high, stock market is shallow, domestic saving is low.

- **Imperfect capital market justification**: if the capital cannot find its way to the infant industry, then government intervention may be able to help.

## Import-substitution

- The orientation of trade protection is inherently domestic oriented instead of export oriented.

- **Import substiting Industrialization (ISI)** is when a country limit import competition to replace it with domestic production.

- Choosing ISI = choosing not to pursue export orientation growth:

    - protection skews up prices of importing industries relative to exporting industries,
    
    - factor of production akan geser ke importing industries, M naik, X turun.
    
## ISI

- ISI most often ended up accompanied by increased FDI.

    - The trade vs FDI trade-off (market seeking).
    
    - Large countries (e.g., Indonesia) has advantage in attracting FDI.
    
    - Small markets typically encourage export-promotion strategy.

- It typically began by protecting consumer goods (food processing & automobile).

- Then protects intermediate goods (steel, petrochems).

## Does ISI work?

- The discussion on ISI vs free trade is a dynamic one.

    - pre-80s $\rightarrow$ pro ISI.
    
    - 80s-2000s, $\rightarrow$ pro free trade.

    - Since GFC & the rust belt, ISI is back.
    
- One thing remains: which one is better for welfare?

    - ISI helped manufacturing in Latin America but not the economy in general.
    
## Why ISI fails?

- It is possible the protection is given to an industry with a comparative disadvantage anyway.

    - If this is the case, then the industry will be forever infant.
    
- e.g., lack of skilled labor, expensive financing, bad organisation.

    - Changing these may require policies, but NOT trade policies.
    
## Why ISI fails?

- Protection such as quotas & LCR are <u>complicated</u> & leads to high tariff-equivalent ([49% in IDN](https://theconversation.com/jangan-dibatasi-impor-bahan-makanan-bisa-perkuat-perekonomian-dan-ketahanan-pangan-192625))

- It is also harder to calculate cost & benefits than simple tariff.

- ISI may skew incentive toward rent seeking activity instead of productivity improvement.

- ISI forces firms to limit its market, lose economies of scale.

    - IDN market is large but not as large as China, US or EU.
    
## Trade liberalization

- Happens mostly in 1985, along with **financial liberalization**.

- This leads to higher trade activity in developing countries, and more manufacturing goods trade as opposed to agricultures & mining goods.

- But trade liberalization, like ISI, we need to be critical on its impact on economic growth. 

- The answer is mixed: Latin American Countries' growth actually slows along with these liberalization, while India, China and The Asian Tigers were growing much more rapidly.

## Asian Growth

- The Asian Tigers (Taiwan, South Korea, Hong Kong and Singapore) experienced an amazing growth during these times.

    - later, it's India and China.
    
- These countries conducted various policy changes, among them is a freer trade regime.

    - However, it is hard to attribute the success only to this policy changes.
    
    - Latin America and Mexico experienced similar level of liberalization with no significant economic growth.

## Recent developments

- usually, arguments for & against trade revolves around these debates.

- These days, new arguments arrived: we have arrived in another flip in trade policy discussions.

- More arguments for activist trade policy: technology externality, labor issues, and environment externality.

## Tech externalities

- Knowledge activities produce technologies which can be used by everyone.

    - This leads to less people want to innovate because others will free ride.
    
- Intelectual properties can be used, but:

    - sometimes other firms can produce better products than the innovators. (think of android vs iOS)
    
    - Kinda limited.
    
- Targeting the right activity is non-trivial.

## The tech industries

- In the 80s, US was losing grip with the manufacturing of Random Access Memories (RAM) to Japan (and then South Korea)

- This in turns snowball to downstream hardware industries.

- US was fine because they dominates the emerged internet industries (the softwares).

## The tech industries

- However, the worry over control over hardware productions return.

- Intel founders [Andy Grove](https://www.bloomberg.com/news/articles/2010-07-01/andy-grove-how-america-can-create-jobs?leadSource=uverify%20wall) argues the importance of having a hardware industries near the place where software industries thrives.

- In effect, he argues innovation in hardware and software are externalizing each other and should be closely linked.

## The tech industries

- Our analysis pre-UTS suggests that US focusing on IT & less on hardwares should be fine.

    - Apple and others can keep inventing in chip design because they do not have to invest in building chip factories.
    
- However, if it is true that having domestic chip foundries can provide externalities with the innovation as well, then it may warrant a good justification for intervention.

- This debate requires good number crunching to settle.

## Globalization and wage

- low-value manufactured goods (e.g., textiles) coming from developing countries:

    - produced by lower wage labors.
    
    - low standard working condition (e.g., [bangladesh plaza collapse](https://en.wikipedia.org/wiki/2013_Rana_Plaza_factory_collapse)).
    
- Seharusnya working standard & wage di Bangladesh mendekati AS, kan? (factor price equalisation)

## Globalization and wage

- Menurut standard trade theory, benar bahwa pekerja di negara dengan labor yang tidak banyak akan merugi.

- Namun, pekerja di negara dengan labor yang banyak masih lebih untung dibanding jika tidak globalisasi.

    - meski wage-nya rendah, namun income dari export memberi mereka akses pada barang yang mahal jika dibuat sendiri di dalam negeri.
    
## Globalization & labor standard

- Dorongan de-globalisasi juga datang dari argumen working condition.

- Dorongan ini sudah sering muncul, tapi trigger utamanya adalah runtuhnya pabrik garmen di Bangladesh yang menewaskan 1.200 pekerja.

- Negara berkembang bisa menekan cost dengan menekan labor standard $\rightarrow$ "race to the bottom"

- Konsumen harus tau supply chain barang konsumsinya jika ingin mengurangi _footprint_ labor standard yang buruk.

## Globalization & labor standard

- Sekarang, advokasi untuk membuat labor standard yang baik semakin gencar.

- Labor standard menjadi fokus AS dalam membuat FTA baru maupun kebijakan perdagangan lainnya.

    - banyak perusahaan juga mensyaratkan supply chain yang bebas dari problem HAM bagi supliernya.

- _pushback_ dari developing countries: labor standard hanya akan jadi alat proteksionisme.

## Globalisasi & alam

- Argumen yg sama: permintaan negara maju mendorong negara berkembang merusak alam:

    - praktik buka hutan yang eksesif untuk kayu, perkebunan, dan pertambangan.
    
- Trade membuat kapal semakin besar & sering jalan $\rightarrow$ more emission.

- **pollution haven**: Negara maju mengekspor polusi dengan membuat pabrik di negara berkembang dengan standar lingkungan yang lebih rendah (evidence untuk ini masih mixed).

## Carbon tariff

- Countries with strong environmental standard + carbon trading mechanisms imposes carbon tariffs to level the playing field.

- Carbon tariffs reduces the possibility of pollution haven and may encourage accepting environmental standard embedded in an FTA.

- Naturally, developing countries criticise this: developed countries will demand too high of a standard, and used as a protection.

## Globalisation & communities

- Some industries may be highly concentrated in a location in a country, it becomes a culture.

- This argument rise importance after the finding of [Autor et al. (2013)](https://www.aeaweb.org/articles?id=10.1257/aer.103.6.2121):

    - Imports from China reduces manufacturing jobs in the US.
    
    - While the reduction is relatively small, it is highly concentrated in a small area.
    
    - Those areas' demand for domestic services dies with it.
    
## Issues in trade

- The ISI comeback

- Technology externalities

- Labor wage and standard

- Environments

- Communities

## Trade is more than numbers

- There are more issues in trade that models alone consider.

- However, some of these arguments are less technical with little calculation to support them.

- Additionally, most of these problems can be countered by good domestic policies instead of a trade policy.

- next week: the new industrialisation policy.