---
title: "Ilmu Ekonomi"
subtitle: "Pertemuan 1"
author: "Prodi PIWAR Politeknik APP Jakarta"
format: 
  revealjs:
    theme: [simple,../mytheme.scss]
    chalkboard: true
    incremental: false
    transition: convex
    background-transition: fade
    slide-number: true

---

## Today's content ☀

- housekeeping
- about studying economics
- some main principles

## About the content of PIR2317 📚

- This course is based on [Krugman and Wells (2016)](https://www.periplus.com/p/9781464186653/essentials-of-economics?filter_name=essentials%20of%20economics).
- covered are principle of microeconomics:
  - Supply and demand
  - the market and its limitation
- and macroeconomics:
  - GDP, inflation, unemployment, the government
  - What does it mean for business
- books can be useful but are not required.

---

## Some expectations from student

- No prior knowledge is required.
- Please be active and ask questions.
- Do your assignments & be active.
- No cheating! Especially during exams.

## Some rules

- The lectures will be about 1.5 - 2 hours length.
- I expect all students to pay attention.
  - I would greatly appreciate you turning on your cams.
- Feel free to interrupt my class with questions.
- email me at imade.krisna@poltekapp.ac.id  

---

{{< slide class="table" >}}

## Structure of this course

- week 1: introduction
  - housekeeping
  - some principles

- week 2: supply and demand
  - supply and demand curves
  - perfect market equilibrium

- week 3: Meddling with the market
  - tax and quantity control
  - price elasticity

- week 4: firm problem
  - production function
  - marginal cost and average cost
  - perfect competition

---

{{< slide class="table" >}}

## Structure of this course

- week 5: Monopoly & oligopoly
  - price discrimination
  - game theory intro

- week 6: Externalities & public goods
  - deviation from perfect market
  - policies that work

- week 7: Welfare
  - Poverty & inequality
  - firms under different welfare setting

*** MIDTERM EXAM ***

---

{{< slide class="table" >}}

## Structure of this course

- week 8: Macro basics
  - accounting and growth
  - inflation and international imbalances

- week 9: GDP, inflation and unemployment
  - Measuring economy and price
  - unemployment

- week 10: Long run growth
  - Dynamics of economic growth
  - Aggregate demand and supply

- week 11: Fiscal policy
  - demand shock
  - the state budget
  
---

{{< slide class="table" >}}

## Structure of this course

- week 12: Financial system
  - Banks and money
  - The central bank
- week 13: Monetary policy
  - interest rate
  - central bank instruments

- week 14: international economies
  - trade policy
  - international capital and exchange rate

---

## Exams etc ✍🏾

| evaluation | covers | % |
| ---------- | ------ | - |
| Group assignment | contextual | 40 |
| midterm exam | first 7 meetings | 30 |
| final exam | all meetings | 30 |  

- Slides should be enough to get a good grade.
- However, to get an A, you should master the principle.

---


## Some tools

- All course materials are accessible through lentera and [google classroom](https://classroom.google.com/u/1/c/MjY5NTUzNzc0NTg5) in pdf.
- All announcement will be posted on lentera and google classroom.
  - I believe it will patch through your Petra e-mail as well.
  - Feel free to let me know what's best for your learning.
- The course is also available at my website, [s.id/econ101]({{< relref "/courses/econ101" >}}).
  - It is in html format so you don't have to download.
  - Also can be viewed on your phone.
- I will update the course on a weekly basis.

---

## Some tools

- The mid-lecture pop quiz (ungraded) will be conducted via poll everywhere.
  - Please prepare a tab in your browser to [pollev.com/imedkrisna007](https://pollev.com/imedkrisna007/)
  - You can also use your smartphone's browser.

- The tool for the end-lecture quiz (graded) is still being explored.
  - we will test [quizizz](https://joinmyquiz.com/) by the end of today's lecture.
  - We can also use google form.
  - You are free to let me know your preference.

---

# Questions?

---

## A bit about you

<iframe src="https://embed.polleverywhere.com/multiple_choice_polls/ZSvuqLVH3kXDtyC0q1VL0?controls=none&short_poll=true" width="800px" height="600px"></iframe>

---

## A bit about you

<iframe src="https://embed.polleverywhere.com/free_text_polls/8I0gGEvVFCiSryr6tM8Fh?controls=none&short_poll=true" width="800px" height="600px"></iframe>

---

## Now let's appoint a class rep!

- for now, class rep's responsibility is to just administering attendance.
- any student is allowed to contact me directly.

---

# About economics

---

## Why economics?

- Contrary to what normal people think, economics is not about (just) money.
- Economics is all about making optimal decision under scarcity.
- We use math principle to optimise our decision making.
- This course is not going to dig too deep into the world of economic principles.
- This course does not provide answers to your question: It teach how to use economic framework to shape your question.

---

## Some questions asked by economists

- How to best tackle climate change?
- Is minimum wage good?
- Should we introduce tax holiday to firms?
- Should the government increase expenditure by more tax or more debt?
- Should we introduce Universal Basic Income?
- How to evaluate government program?
- Should we ban mineral export?
- can we sustain economic growth?
- what to do during economic crisis?

---

## More questions can be answered with (partially) economic principles

- lockdown or not lockdown?
- Should we invest in testing and tracing? or should we invest in treatment?
- Who to vaccine first: the elderly and vulnerables, or the working age?
- Should we trust BUMN, or private sector?
- essentially, it's about tradeoffs, cost and benefit.

---

### About your learning

- To get a glimpse of what economists usually do, you can take a look at my blog. examples:
  - [Consumption-saving decision]({{< relref "post/surga" >}})
  - [how to set the price on toll road]({{< relref "post/jorr" >}})
  - [FDI, trade and industry policy (in Indonesian)]({{< relref "post/hitektrade" >}})

-  Questions you might be interested in:
   - should I expand to other market or continue serving my niche?
   - Should I outsource or make our own?
   - Recruit fresh grads or train high school graduates?
   - Update current system or adapt new system?

---

# Principles of Economics 💰

---

### People make choices

##### because resources are scarce

- resource can be anything you use to produce.

- Money is the most mainstream limited resource.
  - Buy only one holiday package.
  - Buy only one portion of nasi goreng.

- But there are other resources worth noting.
  - There's only one holiday season in a year.
  - Two nasi gorengs would be too much for my stomach.

---

### The true cost of something is its opportunity cost

- money is just one type of cost.
- The true cost of taking a holiday to Hong Kong is going somewhere else.
- Your holiday can be spent on learning new stuff.
- What is the cost of doing your degree?
  - Going straight to work and get experiences.
  - Doing other degrees (biology, chemistry, etc).
  - enjoy life.
- essentially, opportunity cost of something is something else you gave up to get it.

---

### Pop quiz

<iframe src="https://embed.polleverywhere.com/multiple_choice_polls/27Z726hL5mMDWeaKsBbDQ?controls=none&short_poll=true" width="800px" height="600px"></iframe>

---

### Thinking at the margin

- The principle of opportunity cost leads to a marginal thinking.
- Understand your status quo, and think what action you can do to add a little improvement from it.
- If you have two hours to study or play, how will you divide it?
  - what if there's an exam tommorow?
  - If you are tired of studying, would you study more?

---

### Specialisation and gains from trade

- During your daily time, you make decisions on allocating how much time to study and to cook, among other things.
- Since you will die if you don't eat, you can't allocate 0 hour to cook.
- On the other hand, there are those who are very good cook and will cook for you for a little money.
- In this case, it may be better if you spend 0 hour to cook, and order food from these chefs.
- Trade is the reason why I can study economics: I don't have to study how to be a doctor. I will just go to the hospital if I need a medical service.

---

### Specialisation and gains from trade

- Extending to firm level, many outsource part of their business from a third party.
  - buying {{< icon name="microsoft" pack="fab" >}}office probably better than developing our own softwares.
  - why make our own server if we can use {{< icon name="aws" pack="fab" >}}?
  - Use tokopedia instead of making your own e-store.

- We can easily extend this to a country level:
  - Japan makes car because they cannot plant palm oil.

---

### Incentives matter

- People move to cities because there are more opportunities there.
- People will buy cheaper products given the same price.
- incentives are not always about money:
  - You study more on the subjects you like.
    
> *"ada gula ada semut"*

---

### Market and intervention

- often times, market incentives are enough.
- However, intervention is often used.
  - education is an example where government intervene heavily.
  - Gojek used subsidy to incentivies drivers and users.
- Intervention may be temporary.
  - The COVID-19 relieve bill (PEN) will likely stop after the pandemic.
  - Gojek's subsidy is removed once they reach economies of scale.

---

### Things tend to move to equilibrium

- When there is an incentive to do something, there will be more and more people exploit it.
- As more people do it, the incentive decreases to a point where it is not worth it anymore.
- examples:
  - City becomes more crowded (and costly to live in).
  - Stock price stops growing few moments after its IPO.
  - Countries' economic growth reduced after they get rich.
- Movement towards equilibrium, however, varies.
  - short run vs long run.
  - individual vs aggregate.
  
---

### Conclusion

- We will see how these principles come up again and again as we delve deeper into the course.
- The principle will be carried over to your overall degree, and life in general.
- I am not trying to make you an economist, but the principles are very useful.

---

## Testing Graded quiz

---

## Housekeeping!

- Joy is the class rep.
- We'll use Zoom over Google Meet.
- Quizizz is used for everyday lecture.
- what else?

---

## Next week: Supply and demand