---
title: "Reviewing the exchange rate"
subtitle: "ECEU603002 Keuangan internasional"
date: "5 September 2024"
date-format: "long"
author: "I Made Krisna Gupta"
format: 
  revealjs:
    theme: [simple,../mytheme.scss]
    chalkboard: true
    incremental: false
    transition: convex
    background-transition: fade
    slide-number: true
  beamer: default
  pptx: default
---

## Reminder

- Your lecturer pre-midterm is I Made Krisna aka [Imed](https://krisna.or.id).

    - contents are mostly to catch you up with trade theories.

- Kiki Verico will handle post-midterm.

- As discussed, we will use contents from Feenstra & Taylor's International Macroeconomics.

- Slides, homeworks, and announcements will be on EMAS (at least pre-midterm).

## Eploring questions

1. Fitur apa dari nilai tukar yang perlu kita perhatikan?
2. Bagaimana operasionalisasi pasar uang?
3. ekspektasi dan arbitrasi penting. KOk bisa?

## Pendahuluan

- Nilai tukar sangat berpengaruh pada perdagangan internasional barang dan jasa, tapi juga jual beli aset keuangan.

- Dampak ini datang lewat harga barang dan jasa, serta harga aset (bonds, stocks, harga rumah dan lain lain)

- Perdagangan di pasar uang bernilai triliunan dolar dan terkadang memiliki implikasi yang sangat besar.

## Topik hari ini

- Dasar dari nilai tukar

- Fakta tentang pergerangan nilai tukar

- Pasar uang

- Arbitrase dan ekspektasi

## Dasar nilai tukar {.m}

- Nilai tukar (E) adalah harga satu mata uang yang diekspresikan/dinilai/divaluasi dalam mata uang lain.

- Karena nilai tukar pada dasarnya adalah harga relatif, maka E dapat diekspresikan dengan dua cara:

    - Rupiah yang diperlukan untuk membeli 1 unit mata uang lain; atau
    
    - Mata uang lain yang diperlukan untuk membeli 1 unit rupiah.
    
- Biasanya kami jelaskan mana yang menjadi _home country_ dan mana yang jadi _foreign country_.

- Misalnya ketika kita bicara tentang Indonesia sebagai _home country_, maka nilai tukar Indonesia akan diekspresikan sebagai rupiah yang diperlukan untuk 1 dolar AS.

## Harga USD

| Jenis Valuta | May-24 | Jun-24 | Jul-24 |
| ------- | --- | --- | --- |
| EUR |  0.92 |	 0.93 |	 0.92 |
| GBP | 0.78 	| 0.79 	| 0.78 |
| IDR |  16,253.00 |	 16,375.00 	| *16,260.00* |
| SGD |  1.35 |	 1.36 |	 1.34 |
| CNY |  7.24 |	 7.27 |	 7.23 |

: Nilai tukar Dolar AS ([Tabel IX.6 SEKI](https://www.bi.go.id/id/statistik/ekonomi-keuangan/seki/Default.aspx#headingFour))

$E_{\$/Rp}=6.15\times 10^{-5}$ U.S. exchange rate (America terms)
$E_{Rp/\$}=16,260.00$ Indonesian exchange rate (Indonesian terms)

Note that we usually switch this up in the news.

## Apredepre

- Jika 1 Rp dapat membeli lebih banyak dolar, kita katakan Rp *menguat*, *naik harga*, atau *apresiasi* terhadap dolar.

- Jika 1 Rp dapat membeli lebih sedikit dolar, kita katakan Rp *melemah*, *turun harga*, atau *depresiasi* terhadap dolar.

- Jika Rupiah menguat terhadap Dolar, maka Dolar melemah terhadap Rupiah.

- Karena kita biasa menulis nilai tukar rupiah sebagai $E_{Rp/\$}$, maka angkanya jadi kebalik. Angkanya naik = depresiasi.

- Apresiasi dan depresiasi biasanya diekspresikan dalam persen, atau $\frac{E_{t}-E_{t-1}}{E_{t-1}}$

## Apredepre

| Jenis Valuta | May-24 | Jun-24 | Jul-24 |
| ------- | --- | --- | --- |
| IDR |  16,253.00 |	 16,375.00 	| *16,260.00* |

Rupiah 




