---
title: "Konsep Probabilitas Part 2"
subtitle: "Pertemuan 5"
author: "Matematika & Statistika"
format: 
  revealjs:
    theme: [simple,../mytheme.scss]
    chalkboard: true
    incremental: false
    transition: convex
    background-transition: fade
    slide-number: true
---

## Minggu ini

## Distribusi frekuensi

## Distribusi normal

```{r}
library(tidyverse)
grafik<-function(dataset,...) {
  dataset |>
    ggplot(aes(...))+
    scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0))+
    theme_classic()+
    theme(axis.title.x = element_text(hjust=1),
        axis.title.y = element_text(angle=0,hjust=1,vjust=1),
        panel.grid=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        legend.position=c(1,1),
        legend.justification = c(1,1),
        legend.spacing=unit(0,"cm"),
        legend.margin=margin(0,0,0,0),
        panel.background = element_rect(fill = "#f0f1eb",
                                        colour = "#f0f1eb"),
        plot.background = element_rect(fill = "#f0f1eb"),
        legend.key = element_rect(fill = "#f0f1eb",linetype = "blank"),
        legend.background = element_rect(fill="#f0f1eb"))
}  
dat<-data.frame(x=c(0,1))

wew<-seq(0,1,0.01)

sd1 <- function(x) {
    y <- dnorm(wew, mean = 0.5, sd = 0.1)
    y[x < 0.4 | x > .6] <- NA
    return(y)
}
sd2 <- function(x) {
    y <- dnorm(wew, mean = 0.5, sd = 0.1)
    y[x < 0.3 | x > .701] <- NA
    y[x > 0.4 & x < .6] <- NA
    return(y)
}
sd3 <- function(x) {
    y <- dnorm(wew, mean = 0.5, sd = 0.1)
    y[x < 0.2 | x > .8] <- NA
    y[x > 0.3 & x < .7] <- NA
    return(y)
}

dat |>
  grafik(x=x)+
  stat_function(fun=dnorm,args=list(0.5,0.1),size=1.1)+
  stat_function(fun=sd1,geom="area",fill="lightgreen",alpha=.3)+
  stat_function(fun=sd2,geom="area",fill="lightpink",alpha=.3)+
  stat_function(fun=sd3,geom="area",fill="lightblue",alpha=.3)+
  geom_vline(xintercept=.5)+
  labs(x="X",y="f")

```

```{r}
funcShaded <- function(x) {
    y <- dnorm(x, mean = 0.2, sd = 0.1)
    y[x < 0.42 | x > (0.2 + 4 * 0.1)] <- NA
    return(y)
}
```