---
title: "Exchange rate I: the monetary approach in the long run"
subtitle: "ECES905205 pertemuan 3"
date: "12 September 2024"
author: "I Made Krisna Gupta"
format: 
  revealjs:
    theme: [simple,../mytheme.scss]
    chalkboard: true
    incremental: false
    transition: convex
    background-transition: fade
    slide-number: true
  beamer: default
  pptx: default
---

## Goals

- We set out long-run relationships between money, prices and exchange rates.

- Two parts of development:

    - Purchasing power, linking exchange rate and prices in different countries.
    
    - Linking price levels and monetary conditions in each countries.
    
- Combination of the two: the monetary approach to exchange rates.

## Purchasing power parity

- Since goods can be traded, arbitrage can happen, thus prices can converge in the international market.

- Applied to a single good, we call this "law of one price" (LOOP).

- Applied to a basket of goods, we call this "purchasing power parity".

- We start by assuming a frictionless trade (no trade cost).

## LOOP {.m}

With competitive market, flexible prices and zero trade cost, prices of identical goods sold in different countries should be the same.

For a good $g$ sold in 2 places:

$$
q^g_{ID/US}=E_{Rp/\$}\frac{P^g_{US}}{P^g_{ID}}
$$

Where $q^g_{ID/US}$ is the relative price of good $g$ in Indonesia vs the US. Loop is hold if $q^g_{ID/US}=1$.

## LOOP

If LOOP is hold, we can rearrange the equation above to get:

$$
E_{Rp/\$}P_{US}^{ID}=P^g_{US}
$$

which means the exchange rate must be equal to the ratio of prices expressed in two currencies.

$$
E_{Rp/\$}=\frac{P_{ID}}{P_{US}}
$$

## Purchasing power parity

- PPP is the macroeconomic version of LOOP. We compute two basket of goods in each location, find their local prices, and compare them.

$$
q^g_{ID/US}=E_{Rp/\$}\frac{P^g_{US}}{P^g_{ID}}
$$

- If there are no arbitrage, then the same basket of goods in two countries should have the same price. i.e.,$q^g_{ID/US}=1$

- PPP thus holds: price levels in two countries are equal when expressed in common currency. This is called absolute PPP.

## Real exchange rate

- The real exchange rate is the relative price of the baskets.

- The Indonesian real exchange rate $q^g_{ID/US}=E_{Rp/\$}P^g_{US}/P^g_{ID}$ tells us how many Indonesian baskets are needed to purchase U.S. basket.

- The exchange rate for currencies:

- 