---
title: "The new industrial policy"
subtitle: "ECES905205 pertemuan 7"
date: "10 Oktober 2023"
author: "I Made Krisna Gupta"
format: 
  revealjs:
    theme: [simple,../mytheme.scss]
    chalkboard: true
    incremental: false
    transition: convex
    background-transition: fade
    slide-number: true
  beamer: default
---

## Last Week {.m}

- Argument pro-trade
    
    - specialisation, economies of scale, productivity selection, varieties.
    
- Argument against free trade:

    - Zero-sum-game for losers (usually better organized)
    
    - Zero-sum-game for large countries (leads to FTAs)
    
    - Dynamic efficiency: infant industry.
    
- For any justified government intervention, domestic policies should perform better than trade policies.

## The new industrial policy

- Industrial policy yg terbaru muncul seiring dengan meningkatnya isu-isu politik dan distribusi pendapatan pekerja.

- Meski Amerika Serikat terlihat semakin tertutup semenjak terpilihnya Donald Trump, tapi sebenarnya birokrasinya sudah lama memiliki kekhawatiran terhadap globalisasi sejak Obama.

- Argumen terhadap industrial policy baru masih berada di sekitar _market failure_

- Meski demikian, new industrial policy menitik beratkan menghindari _government failure_

## What is industrial policy?

- **Industrial policy**: policies which **goal** targets the growth or employment of a certain sectors.

    - key part is actively championing a certain sector/firm over others.

- Siglitz, Chang: Any policy is industrial policy, including free market!

    - boosting STEM benefits STEM-using industries, free market helps boost financial services, infrastructure projects benefit industry native to that location.
    
    - To them, IP is about the instrument rather than the goal.

## Old vs new industrial policy

- Debates on industrial policy evolves with economic tools that evaluates them.

    - that market is imperfect and has its own failures.
    
    - capital market liberalization that leads to more crises.
    
- The best praactice changes amid GVC, global financialization, and global rules of trade & economic system.

    - less emphasize on trade policies
    
## Old vs new

| Old paradigm | New paradigm |
| ---------- | ---------- |
| Always bad: govt failure > market failure | Both present. addressing market failure is important to be rich |
| Focuses on why (theoretical) | Focuses on how (empirics & policy evaluation) |
| Use comparative advantage | build new comparative advantage |
| Dealing with govt failure by reducing their role | Focus on institutional setting |
| Domestic oriented | Global oriented |

## More market failure {.m}

- **Coordination problem**: A new sector needs to reach a critical scale to be viable.

    - tool makers won't make tools unless the industry that uses it exists, but the industry won't exist without tool makers.
    
    - Why study data science if there are no data collectors & industries that use data science? OTOH, firms won't come if they cannot find talent.
    
    - remember external economies of scale & agglomeration?
    
- Coordination matters on how much to produce: too much, then not enough profit to upscale.

    - notice this is practically a collusion!

## More market failure

- **Learning externalities**: sometimes firms do not know what products can succeed in the market, what kind of market they are entering (especially in the export market).

- Sometimes market solve this:

    - Vietnam's destination for electronic industries was discovered by Intel, Samsung entering the foldable market.
    
- Sometimes it requires a push from the government, particularly amid spillover effect.

## More market failure

- **Imperfect capital market**: Developing countries lack good quality financial institutions, hence more credit constraints.

- However, evidence emerges since the various crises that the market is not as efficient in general.

    - More crises since 1980s, the age of financial liberalization.
    
- Even in the developed world, finance does not come to the promising future industries.

## Government failure

- State intervention is as old as the state itself.

- Justru solusi berbasis pasar baru-baru ini saja digunakan untuk mengatasi government failure.

- Rent-seeking by sectors, corruption, inefficient SOEs, mercantilist pressure, land & real estate grabbing.

- Failed to plan exit strategy: forever infant.

## Design principle

1. Kejar industri teknologi baru / multiplier besar.

1. Accountability from the receiver of supports. Misalnya, requires performance targets, ada exit clause: when to grow up, what if forever infant.

1. Maintain competition both domestic and globally.

1. Serahkan evaluasi ke independent experts. (Australia: Productivity Comission, Indonesia: UKP4)

1. Kontrol terhadap korupsi.

## Decision-making framework {.m}

1. Targeting: Which sectors & why? What are the market failures? Do we have enough resources to deal with the market failure? What is the goal to impose to this sector? (jobs created, new tech discovered, how much exports, etc) 

1. Implementation: How to assist? What type of public supports are needed? How long should they last? Can we minimize government failures? How to monev?

1. Governance: who decides which sectors to target? Who is the PIC of which intervention? Who conducts the monev? Who coordinates the action plan? Who collect market feedbacks?

## Which sectors?

- Cherif & Hasanov (2019): Often emerge in a tradable goods & services sectors with high degree of R&D and high-skill labors.

- The argument for new industrial policy requires a newly emerged industries, not an old one.

- Examples: high-tech manufacturing, transportation, communications, financial intermediaries, business services (Cherif et al. 2022), 

- Other industries? Solve the **government failure** first!

## Cost-benefit test

- Must conducted rigorously: capital & labor's opportunity cost

    - unless labor are taken from unemployment.
    
    - demand for capital can be seen in growth of consumer credit relative to production credit.
    
- Assessing cost is often easier than benefit amid uncertainty (another market failure).

- The government must be prepared to absorb loss (but this is exactly why industrial policy was scrutinized).

## Tools: goods market {.m}

- Many classic trade tools (tariff and NTMs) are prohibited by trade agreements.

    - Engaging with global market is essential for capital, inputs, and competition.

- Export promotion: lower income tax from export revenue, import subsidies for important inputs, export credit subsidies.

- Attracting FDI (for spillover purposes) with tax incentives often too costly with little benefit.

- Tax incentives to use domestic supplies works better than LCR.

- Provide certainty of demand from government procurement.

## Tools: labor market

- Training for workers with specific skills required by the targeted industry.

    - improve vocational education & training.
    
    - work very closely with the industry.

- tax incentives to encourage apprenticeship.

- Avoid rigid labor regulations.

## Tools: capital market

- tax incentives for capital investment.

- Direct lending has mixed results, require general knowledge of credit constraint.

    - interest payment subsidy also mixed, with a fiscal burden on top.
    
- Credit guarantee can create moral hazard.

- Indonesia is much more conservative after 1998.

## Other tools

- Special Economic Zones: encourage agglomeration, reduces uncertainty in the land market, and can be subject to special price for land. Additionally, can be controlled by the central government.

- R&D subsidy (or via tax incentives), or direct R&D using the state budget.

    - U.S.' DARPA is a great example of the emerging internet-based industries.
    
- Macroeconomic stabilisation may benefit one sector than others (e.g., international borrowings vs exports).

## Financing industrial policy

- New industrial policies emphasize on the use of global market instead of import substitution.

- Mostly use tax incentives or some type of subsidies.

- Rich countries with AAA bond ratings are in better position to finance their industrial policies.

- Using tax incentives may reduces other welfare improving programs, and may reduce evaluation budget.

## Typical problems in evaluation

- Endogeneity of treatment: industrial policy typically assigned non-randomly.

    - researchers usually rely on natural experiments.
    
    - Better evaluation design requires a degree of randomness, or at least quasi-experiments.

- Just because policy exists does not mean it will be used.

- Lack of attention given to evaluation process: data procurement and monev.

## Tugas

- Industrial policy is extremely broad, but all policies created must be in harmony.

- Select one regulation on industrial policy, and see if you can use the framework in today's lecture to assess the selected regulation!

- Has government done this? If so, you can try to criticise the government's decision framework!

- Next week: international finance.

## References {.s}

- Aiginger, K., & Rodrik, D. (2020). Rebirth of Industrial Policy and an Agenda for the Twenty-First Century. Journal of Industry, Competition and Trade, 20(2), 189-207. https://doi.org/10.1007/s10842-019-00322-3 

- Chang, H.-J., & Andreoni, A. (2020). Industrial Policy in the 21st Century. Development and Change, 51(2), 324-351. https://doi.org/https://doi.org/10.1111/dech.12570 

- Cherif, R., & Hasanov, F. (2019). The Return of the Policy That Shall Not Be Named: Principles of Industrial Policy. IMF Working Paper, 19(74). 

- International Monetary Fund. (2022). Industrial Policy for Growth and Diversification: A Conceptual Framework. IMF Departmental Paper. 

- Stiglitz, J. E. (2015). Industrial policy, learning, and development. WIDER Working Paper 2015/149. https://www.wider.unu.edu/publication/industrial-policy-learning-and-development 

- Wim, N. (2010). Industrial Policy. In (Vol. 2010). Helsinki, Finland: UNU-WIDER.
