<!DOCTYPE html>
<html lang="en"><head>
<script src="kg_toyotatsusho_files/libs/clipboard/clipboard.min.js"></script>
<script src="kg_toyotatsusho_files/libs/quarto-html/tabby.min.js"></script>
<script src="kg_toyotatsusho_files/libs/quarto-html/popper.min.js"></script>
<script src="kg_toyotatsusho_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="kg_toyotatsusho_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="kg_toyotatsusho_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="kg_toyotatsusho_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="Krisna Gupta">
  <meta name="dcterms.date" content="2026-07-28">
  <title>Indonesia’s Economy in 2026</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="kg_toyotatsusho_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="kg_toyotatsusho_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="kg_toyotatsusho_files/libs/revealjs/dist/theme/quarto-6a0936f214d018485b9e1b578c23d634.css">
  <link href="kg_toyotatsusho_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="kg_toyotatsusho_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="kg_toyotatsusho_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="kg_toyotatsusho_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="kg_toyotatsusho_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="kg_toyotatsusho_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Indonesia’s Economy in 2026</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Krisna Gupta 
</div>
</div>
</div>

  <p class="date">2026-07-28</p>
</section>
<section id="about-me" class="slide level2">
<h2>About me</h2>
<ul>
<li><p>Economist at the <a href="https://www.dewanekonomi.go.id">National Economic Council</a> (Dewan Ekonomi Nasional).</p></li>
<li><p>Lecturer at Universitas Indonesia.</p></li>
<li><p>PhD in Economics, Australian National University.</p></li>
<li><p>Research: trade and industrial policy, applied econometrics.</p></li>
<li><p>Say hello at <code>@imedkrisna</code> or read <a href="https://krisna.or.id/">krisna.or.id</a>.</p></li>
</ul>
</section>
<section id="contents" class="slide level2">
<h2>Contents</h2>
<p>Part 1 — Indonesia update</p>
<ol type="1">
<li>Growth: expenditure, industries, manufacturing</li>
<li>Inflation</li>
<li>Liquidity, credit, and capital flows</li>
<li>The S&amp;P rating decision</li>
</ol>
<p>Part 2 — Three themes</p>
<ol start="5" type="1">
<li>Inflation: volatile food and El Niño</li>
<li>Fiscal: the interest bill</li>
<li>Geoeconomics: fragmentation and critical points</li>
</ol>
</section>
<section>
<section id="part-1-indonesia-update" class="title-slide slide level1 center">
<h1>Part 1 — Indonesia update</h1>

</section>
<section id="headline-5.61-percent" class="slide level2 m">
<h2>Headline: 5.61 percent</h2>
<ul>
<li><p>Q1-2026 GDP grew 5.61% y-on-y, well up from 4.87% in Q1-2025.</p></li>
<li><p>But the composition is unusual. Government consumption grew 21.81%, contributing 1.26 percentage points of the 5.61.</p></li>
<li><p>Household consumption, still 54.4% of GDP, grew 5.52% — helped by Ramadan and Idulfitri falling in the quarter.</p></li>
<li><p>Exports grew 0.90% while imports grew 7.18%: net exports subtracted from growth.</p></li>
<li><p>Quarter-on-quarter the economy contracted 0.77%, with government consumption down 30.13% after the Q4-2025 spending surge.</p></li>
</ul>
</section>
<section id="gdp-growth" class="slide level2 s">
<h2>GDP growth</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 17%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>(% y-on-y)</th>
<th style="text-align: right;">2023</th>
<th style="text-align: right;">2024</th>
<th style="text-align: right;">2025</th>
<th style="text-align: right;">25Q1</th>
<th style="text-align: right;">25Q2</th>
<th style="text-align: right;">25Q3</th>
<th style="text-align: right;">25Q4</th>
<th style="text-align: right;">26Q1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GDP</td>
<td style="text-align: right;">5.05</td>
<td style="text-align: right;">5.03</td>
<td style="text-align: right;">5.11</td>
<td style="text-align: right;">4.87</td>
<td style="text-align: right;">5.12</td>
<td style="text-align: right;">5.04</td>
<td style="text-align: right;">5.39</td>
<td style="text-align: right;">5.61</td>
</tr>
<tr class="even">
<td>Household consumption (C)</td>
<td style="text-align: right;">4.82</td>
<td style="text-align: right;">4.94</td>
<td style="text-align: right;">4.98</td>
<td style="text-align: right;">4.95</td>
<td style="text-align: right;">4.97</td>
<td style="text-align: right;">4.89</td>
<td style="text-align: right;">5.11</td>
<td style="text-align: right;">5.52</td>
</tr>
<tr class="odd">
<td>Non-profit institutions</td>
<td style="text-align: right;">9.83</td>
<td style="text-align: right;">12.48</td>
<td style="text-align: right;">5.13</td>
<td style="text-align: right;">3.07</td>
<td style="text-align: right;">7.82</td>
<td style="text-align: right;">3.76</td>
<td style="text-align: right;">5.90</td>
<td style="text-align: right;">6.28</td>
</tr>
<tr class="even">
<td>Government consumption (G)</td>
<td style="text-align: right;">2.95</td>
<td style="text-align: right;">6.61</td>
<td style="text-align: right;">2.50</td>
<td style="text-align: right;">−1.37</td>
<td style="text-align: right;">−0.33</td>
<td style="text-align: right;">5.66</td>
<td style="text-align: right;">4.55</td>
<td style="text-align: right;">21.81</td>
</tr>
<tr class="odd">
<td>Gross fixed capital formation (I)</td>
<td style="text-align: right;">4.40</td>
<td style="text-align: right;">4.61</td>
<td style="text-align: right;">5.09</td>
<td style="text-align: right;">2.12</td>
<td style="text-align: right;">6.99</td>
<td style="text-align: right;">5.04</td>
<td style="text-align: right;">6.12</td>
<td style="text-align: right;">5.96</td>
</tr>
<tr class="even">
<td>Exports (X)</td>
<td style="text-align: right;">1.32</td>
<td style="text-align: right;">6.51</td>
<td style="text-align: right;">7.03</td>
<td style="text-align: right;">6.46</td>
<td style="text-align: right;">10.95</td>
<td style="text-align: right;">9.14</td>
<td style="text-align: right;">3.25</td>
<td style="text-align: right;">0.90</td>
</tr>
<tr class="odd">
<td>Imports (M)</td>
<td style="text-align: right;">−1.65</td>
<td style="text-align: right;">7.95</td>
<td style="text-align: right;">4.77</td>
<td style="text-align: right;">4.17</td>
<td style="text-align: right;">11.48</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">3.96</td>
<td style="text-align: right;">7.18</td>
</tr>
</tbody>
</table>
</section>
<section id="reading-the-expenditure-table" class="slide level2 m">
<h2>Reading the expenditure table</h2>
<ul>
<li><p>G contributed 1.26 pp in Q1-2026 against 2.94 pp from households, despite being one-eighth the size. Salaries (13th-month, THR) and the free nutritious meals programme (MBG) are the drivers.</p></li>
<li><p>the Q1 surge partly reflects the low base of Q1-2025, when government consumption contracted 1.22%.</p></li>
<li><p>Investment growth remains high at 5.96%. Growth enhancing?</p></li>
<li><p>The external sector turned. X at 0.90% against M at 7.18% is the mirror image of 2024–25 — and the monthly trade data confirm it, as the next slide shows.</p></li>
</ul>
</section>
<section id="growth-by-industry" class="slide level2 s scrollable">
<h2>Growth by industry</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 17%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>(% y-on-y)</th>
<th style="text-align: right;">2023</th>
<th style="text-align: right;">2024</th>
<th style="text-align: right;">2025</th>
<th style="text-align: right;">25Q1</th>
<th style="text-align: right;">25Q2</th>
<th style="text-align: right;">25Q3</th>
<th style="text-align: right;">25Q4</th>
<th style="text-align: right;">26Q1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GDP</td>
<td style="text-align: right;">5.05</td>
<td style="text-align: right;">5.03</td>
<td style="text-align: right;">5.11</td>
<td style="text-align: right;">4.87</td>
<td style="text-align: right;">5.12</td>
<td style="text-align: right;">5.04</td>
<td style="text-align: right;">5.39</td>
<td style="text-align: right;">5.61</td>
</tr>
<tr class="even">
<td>Tradables</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td>Agriculture, forestry &amp; fishing</td>
<td style="text-align: right;">1.30</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">5.33</td>
<td style="text-align: right;">10.52</td>
<td style="text-align: right;">1.65</td>
<td style="text-align: right;">4.93</td>
<td style="text-align: right;">5.14</td>
<td style="text-align: right;">4.97</td>
</tr>
<tr class="even">
<td>Mining &amp; quarrying</td>
<td style="text-align: right;">6.12</td>
<td style="text-align: right;">4.90</td>
<td style="text-align: right;">−0.66</td>
<td style="text-align: right;">−1.23</td>
<td style="text-align: right;">2.03</td>
<td style="text-align: right;">−1.98</td>
<td style="text-align: right;">−1.31</td>
<td style="text-align: right;">−2.14</td>
</tr>
<tr class="odd">
<td>Manufacturing (C)</td>
<td style="text-align: right;">4.64</td>
<td style="text-align: right;">4.43</td>
<td style="text-align: right;">5.30</td>
<td style="text-align: right;">4.55</td>
<td style="text-align: right;">5.68</td>
<td style="text-align: right;">5.54</td>
<td style="text-align: right;">5.40</td>
<td style="text-align: right;">5.04</td>
</tr>
<tr class="even">
<td>Non-tradables</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td>Electricity &amp; gas</td>
<td style="text-align: right;">4.91</td>
<td style="text-align: right;">4.77</td>
<td style="text-align: right;">3.10</td>
<td style="text-align: right;">5.11</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">2.86</td>
<td style="text-align: right;">3.55</td>
<td style="text-align: right;">−0.99</td>
</tr>
<tr class="even">
<td>Water, waste &amp; recycling</td>
<td style="text-align: right;">4.90</td>
<td style="text-align: right;">1.56</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">3.32</td>
<td style="text-align: right;">−0.51</td>
<td style="text-align: right;">0.42</td>
</tr>
<tr class="odd">
<td>Construction</td>
<td style="text-align: right;">4.91</td>
<td style="text-align: right;">7.02</td>
<td style="text-align: right;">3.81</td>
<td style="text-align: right;">2.18</td>
<td style="text-align: right;">4.98</td>
<td style="text-align: right;">4.21</td>
<td style="text-align: right;">3.89</td>
<td style="text-align: right;">5.49</td>
</tr>
<tr class="even">
<td>Wholesale &amp; retail trade</td>
<td style="text-align: right;">4.85</td>
<td style="text-align: right;">4.86</td>
<td style="text-align: right;">5.49</td>
<td style="text-align: right;">5.03</td>
<td style="text-align: right;">5.37</td>
<td style="text-align: right;">5.46</td>
<td style="text-align: right;">6.07</td>
<td style="text-align: right;">6.26</td>
</tr>
<tr class="odd">
<td>Transport &amp; storage</td>
<td style="text-align: right;">13.96</td>
<td style="text-align: right;">8.69</td>
<td style="text-align: right;">8.78</td>
<td style="text-align: right;">9.01</td>
<td style="text-align: right;">8.52</td>
<td style="text-align: right;">8.62</td>
<td style="text-align: right;">8.98</td>
<td style="text-align: right;">8.04</td>
</tr>
<tr class="even">
<td>Accommodation, food &amp; beverages</td>
<td style="text-align: right;">10.01</td>
<td style="text-align: right;">8.56</td>
<td style="text-align: right;">7.41</td>
<td style="text-align: right;">5.75</td>
<td style="text-align: right;">8.04</td>
<td style="text-align: right;">8.50</td>
<td style="text-align: right;">7.15</td>
<td style="text-align: right;">13.14</td>
</tr>
<tr class="odd">
<td>Information &amp; communication</td>
<td style="text-align: right;">7.59</td>
<td style="text-align: right;">7.57</td>
<td style="text-align: right;">8.35</td>
<td style="text-align: right;">7.72</td>
<td style="text-align: right;">7.92</td>
<td style="text-align: right;">9.65</td>
<td style="text-align: right;">8.09</td>
<td style="text-align: right;">7.14</td>
</tr>
<tr class="even">
<td>Financial &amp; insurance</td>
<td style="text-align: right;">4.77</td>
<td style="text-align: right;">4.74</td>
<td style="text-align: right;">3.96</td>
<td style="text-align: right;">3.98</td>
<td style="text-align: right;">3.20</td>
<td style="text-align: right;">0.77</td>
<td style="text-align: right;">7.92</td>
<td style="text-align: right;">4.68</td>
</tr>
<tr class="odd">
<td>Real estate</td>
<td style="text-align: right;">1.43</td>
<td style="text-align: right;">2.50</td>
<td style="text-align: right;">3.58</td>
<td style="text-align: right;">2.94</td>
<td style="text-align: right;">3.71</td>
<td style="text-align: right;">3.95</td>
<td style="text-align: right;">3.71</td>
<td style="text-align: right;">3.54</td>
</tr>
<tr class="even">
<td>Business services</td>
<td style="text-align: right;">8.24</td>
<td style="text-align: right;">8.38</td>
<td style="text-align: right;">9.10</td>
<td style="text-align: right;">9.27</td>
<td style="text-align: right;">9.31</td>
<td style="text-align: right;">9.94</td>
<td style="text-align: right;">7.90</td>
<td style="text-align: right;">4.91</td>
</tr>
<tr class="odd">
<td>Public administration</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">6.40</td>
<td style="text-align: right;">3.86</td>
<td style="text-align: right;">4.79</td>
<td style="text-align: right;">4.69</td>
<td style="text-align: right;">4.33</td>
<td style="text-align: right;">1.63</td>
<td style="text-align: right;">6.45</td>
</tr>
<tr class="even">
<td>Education services</td>
<td style="text-align: right;">1.78</td>
<td style="text-align: right;">3.75</td>
<td style="text-align: right;">4.99</td>
<td style="text-align: right;">5.04</td>
<td style="text-align: right;">1.40</td>
<td style="text-align: right;">10.59</td>
<td style="text-align: right;">3.43</td>
<td style="text-align: right;">5.18</td>
</tr>
<tr class="odd">
<td>Human health &amp; social work</td>
<td style="text-align: right;">4.66</td>
<td style="text-align: right;">8.11</td>
<td style="text-align: right;">5.59</td>
<td style="text-align: right;">5.78</td>
<td style="text-align: right;">3.80</td>
<td style="text-align: right;">6.83</td>
<td style="text-align: right;">5.95</td>
<td style="text-align: right;">7.62</td>
</tr>
<tr class="even">
<td>Other services</td>
<td style="text-align: right;">10.52</td>
<td style="text-align: right;">9.80</td>
<td style="text-align: right;">9.93</td>
<td style="text-align: right;">9.84</td>
<td style="text-align: right;">11.31</td>
<td style="text-align: right;">9.92</td>
<td style="text-align: right;">8.71</td>
<td style="text-align: right;">9.91</td>
</tr>
</tbody>
</table>
</section>
<section id="reading-the-industry-table" class="slide level2 m">
<h2>Reading the industry table</h2>
<ul>
<li><p>Manufacturing is the largest sector (19.07% of GDP) and grew 5.04%.</p></li>
<li><p>PMI manufacturing fell to 47.7 in June 2026, its fifth month below 50, and the employment sub-index to 46.9. GDP looks back; PMI looks forward.</p></li>
<li><p>Mining contracted 2.14% for a fourth quarter. The recent commodity price hike may change the number in Q2.</p></li>
<li><p>Electricity and gas contracted 0.99%, its first negative quarter since the pandemic.</p></li>
<li><p>The fastest growers — accommodation and food (13.1%), other services (9.9%), transport (8.0%) — are low-productivity, low-tradability activities.</p></li>
</ul>
</section>
<section id="inside-manufacturing" class="slide level2 s scrollable">
<h2>Inside manufacturing</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 33%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>(% y-on-y, constant prices)</th>
<th style="text-align: right;">Share of GDP 2025</th>
<th style="text-align: right;">2023</th>
<th style="text-align: right;">2024</th>
<th style="text-align: right;">2025</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Manufacturing, total</td>
<td style="text-align: right;">19.07</td>
<td style="text-align: right;">4.6</td>
<td style="text-align: right;">4.4</td>
<td style="text-align: right;">5.3</td>
</tr>
<tr class="even">
<td>Basic metals</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: right;">14.2</td>
<td style="text-align: right;">13.3</td>
<td style="text-align: right;">15.7</td>
</tr>
<tr class="odd">
<td>Machinery &amp; equipment</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">−0.0</td>
<td style="text-align: right;">−0.4</td>
<td style="text-align: right;">14.0</td>
</tr>
<tr class="even">
<td>Other manufacturing; repair &amp; installation</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">−2.1</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">9.2</td>
</tr>
<tr class="odd">
<td>Chemicals, pharmaceuticals &amp; botanicals</td>
<td style="text-align: right;">1.83</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">5.9</td>
<td style="text-align: right;">8.4</td>
</tr>
<tr class="even">
<td>Coal products &amp; oil-gas refining</td>
<td style="text-align: right;">1.78</td>
<td style="text-align: right;">4.2</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">6.9</td>
</tr>
<tr class="odd">
<td>Food &amp; beverages</td>
<td style="text-align: right;">7.13</td>
<td style="text-align: right;">4.5</td>
<td style="text-align: right;">5.9</td>
<td style="text-align: right;">6.4</td>
</tr>
<tr class="even">
<td>Non-metallic mineral products</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">4.1</td>
<td style="text-align: right;">−0.6</td>
<td style="text-align: right;">6.2</td>
</tr>
<tr class="odd">
<td>Fabricated metal, computer, electronics, electrical</td>
<td style="text-align: right;">1.60</td>
<td style="text-align: right;">13.7</td>
<td style="text-align: right;">6.2</td>
<td style="text-align: right;">4.6</td>
</tr>
<tr class="even">
<td>Textiles &amp; apparel</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">−2.0</td>
<td style="text-align: right;">4.3</td>
<td style="text-align: right;">3.6</td>
</tr>
<tr class="odd">
<td>Paper &amp; printing</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">4.5</td>
<td style="text-align: right;">2.6</td>
<td style="text-align: right;">3.4</td>
</tr>
<tr class="even">
<td>Leather &amp; footwear</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">−0.3</td>
<td style="text-align: right;">6.8</td>
<td style="text-align: right;">3.3</td>
</tr>
<tr class="odd">
<td>Furniture</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">−2.0</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: right;">1.6</td>
</tr>
<tr class="even">
<td>Tobacco products</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">4.8</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">−1.4</td>
</tr>
<tr class="odd">
<td>Transport equipment</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: right;">7.6</td>
<td style="text-align: right;">−2.1</td>
<td style="text-align: right;">−2.6</td>
</tr>
<tr class="even">
<td>Wood products</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right;">2.8</td>
<td style="text-align: right;">−3.3</td>
</tr>
<tr class="odd">
<td>Rubber &amp; plastics</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">−3.6</td>
<td style="text-align: right;">1.8</td>
<td style="text-align: right;">−4.1</td>
</tr>
</tbody>
</table>
</section>
<section id="what-manufacturing-growth-is-made-of" class="slide level2 m">
<h2>What manufacturing growth is made of</h2>
<ul>
<li><p>Aggregate manufacturing growth of 5.3% in 2025 is carried by basic metals (+15.7%) despite 1.15% of GDP.</p></li>
<li><p>Food and beverages (7.13% of GDP) at 6.4% is the other engine.</p></li>
<li><p>The labour-intensive, export-facing subsectors are flat or shrinking: textiles 3.6%, footwear 3.3%, furniture 1.6%, wood −3.3%, rubber and plastics −4.1%.</p></li>
<li><p>Transport equipment contracted for a second year (−2.6%).</p></li>
<li><p>growth is concentrated in a capital-intensive extractive-processing chain and in government-financed food demand, not in the tradable manufacturing base that employs people.</p></li>
</ul>
</section>
<section id="the-trade-surplus-is-thinning-fast" class="slide level2 m">
<h2>The trade surplus is thinning fast</h2>

<img data-src="fig/trade.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section id="reading-the-trade-chart" class="slide level2 m">
<h2>Reading the trade chart</h2>
<ul>
<li><p>The surplus fell from USD 15.4 bn to USD 4.0 bn in a single year. Exports grew 3.02%; imports grew 15.24%.</p></li>
<li><p>May 2026 alone was a deficit of USD 1.6 bn — exports USD 23.20 bn against imports USD 24.81 bn, with exports down 5.73% y-on-y and imports up 22.16%. The cumulative figure still reads surplus; the monthly figure no longer does.</p></li>
<li><p>Raw materials and intermediates (+14.4%) and capital goods (+17.5%) are production inputs, consistent with the investment and manufacturing numbers.</p></li>
<li><p>Migas imports rose 27.89%, refined products alone 32.54% in values.</p></li>
<li><p>Exports of nickel and articles thereof rose USD 2.05 bn (+60.88%), while agriculture exports fell 24.95% and mining 8.14%.</p></li>
</ul>
</section>
<section id="inflation-is-back-above-target" class="slide level2 m">
<h2>Inflation is back above target</h2>

<img data-src="fig/inflation_components.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section id="reading-the-inflation-chart" class="slide level2 m">
<h2>Reading the inflation chart</h2>
<p>The chart above shows headline CPI inflation (bars) with its three components as lines — core (65.0% of the basket), administered prices (19.2%) and volatile food (15.8%) — all in percent year-on-year, monthly, January 2025 to June 2026. Source: BPS.</p>
<ul>
<li><p>Headline (3.34%) and core (2.76%) inflation in June 2026 are above the 2.5% target midpoint.</p></li>
<li><p>*Administered prices swung from −6.4% to +12.6% between January 2025 and February 2026: the January–February 2025 electricity discount created a base effect that mechanically flipped sign a year later, then fuel pass-through took over.</p></li>
<li><p>Volatile food at 5.58% has been above 5% for eight of the last twelve months.</p></li>
</ul>
</section>
<section id="liquidity-is-ample-credit-is-not" class="slide level2 m">
<h2>Liquidity is ample; credit is not</h2>

<img data-src="fig/liquidity_credit.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section id="reading-the-liquidity-chart" class="slide level2 m">
<h2>Reading the liquidity chart</h2>
<ul>
<li><p>Base money grows 18.1%, deposits 13.5%, credit 11.5%. Liquidity is being created faster than it is being intermediated.</p></li>
<li><p>Deposit rates fell across every tenor the 6-month rate by 136 bps but the weighted lending rate fell only 48 bps, from 9.20% to 8.72%.</p></li>
<li><p>A widening deposit–lending spread with decelerating credit is the signature of weak loan demand and cautious risk appetite.</p></li>
<li><p>Further monetary easing has limited traction. The constraint is on the demand side of credit, which is a real-sector and confidence problem.</p></li>
</ul>
</section>
<section id="capital-is-flowing-back-in" class="slide level2 m">
<h2>Capital is flowing back in</h2>

<img data-src="fig/capital_flows.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section id="reading-the-capital-flow-chart" class="slide level2 m">
<h2>Reading the capital-flow chart</h2>
<ul>
<li><p>After outflow pressure in Q1-2026 (March: −52.0 tn), Q2 reversed sharply: June alone brought +79.5 tn, and the year to 20 July stands at +108.1 tn net inflow.</p></li>
<li><p>The inflow is SRBI (+174.4 tn), Bank Indonesia’s own short-dated paper. Government bonds added only 9.3 tn, and equities lost 75.6 tn*</p></li>
<li><p>Two supports: MSCI retaining Indonesia’s EM status, and the S&amp;P affirmation in July.</p></li>
</ul>
</section>
<section id="sp-holds-the-rating" class="slide level2 m">
<h2>S&amp;P holds the rating</h2>
<ul>
<li><p>13 July 2026: S&amp;P affirmed Indonesia at BBB/A-2, outlook stable.</p></li>
<li><p>S&amp;P’s rationale: “robust growth prospects, generally prudent macroeconomic policy settings, and relatively light net external and government debt burden compared to peers.”</p></li>
<li><p>It gave weight to the government’s repeated commitment to the 3%-of-GDP deficit ceiling, and to its willingness to cut hard when needed — including trimming the MBG budget by roughly a third.</p></li>
<li><p>On Danantara: S&amp;P does not consolidate SOE and Danantara debt with government debt, judging the likelihood of it crystallising on the sovereign balance sheet to be low.</p></li>
<li><p>Markets responded: the rupiah and the JCI both outperformed regional peers in the week after.</p></li>
</ul>
</section>
<section id="but-sp-is-the-outlier" class="slide level2 m">
<h2>But S&amp;P is the outlier</h2>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Agency</th>
<th>Date</th>
<th>Rating</th>
<th>Outlook</th>
<th>Trigger</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Moody’s</td>
<td>5 Feb 2026</td>
<td>Baa2 (affirmed)</td>
<td>Stable → Negative</td>
<td>Reduced predictability of policymaking; weakening governance</td>
</tr>
<tr class="even">
<td>Fitch</td>
<td>4 Mar 2026</td>
<td>BBB (affirmed)</td>
<td>Stable → Negative</td>
<td>Policy uncertainty; increasingly centralised decision-making; debt service at 17% of revenue</td>
</tr>
<tr class="odd">
<td>S&amp;P</td>
<td>13 Jul 2026</td>
<td>BBB/A-2 (affirmed)</td>
<td>Stable</td>
<td>Fiscal and external strains judged temporary</td>
</tr>
</tbody>
</table>
</section>
<section id="the-hormuz-problem" class="slide level2">
<h2>The Hormuz Problem</h2>

<img data-src="fig/brent.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section id="reading-the-brent-chart" class="slide level2 m">
<h2>Reading the Brent chart</h2>
<ul>
<li><p>Brent opened the year at USD 61 and peaked at USD 138 on 7 April as the Strait of Hormuz escalation ran its course. The monthly average went 67, 71, 103, 117, 107 — a doubling in three months.</p></li>
<li><p>It has averaged USD 90 year to date, 29% above the APBN assumption. The Jan–May average of USD 92.81 is consistent with the ICP outturn of USD 91.87 that APBN Kita reports.</p></li>
<li><p>The de-escalation held only briefly. June averaged 85, July fell as low as 70 — and then turned: Brent is back at USD 87, up 24% from the June trough.</p></li>
<li><p>This single line drives three things already in this deck: the subsidy and compensation bill at 52.1% of budget in six months, administered-price inflation at 3.42%, and the migas import bill up 27.89%.</p></li>
<li><p>For a trading house the point is not the level but the variance. A chokepoint that can move Brent 60% in a quarter is a working-capital and freight-rate problem before it is a macro problem.</p></li>
</ul>
</section></section>
<section id="part-2-three-themes" class="title-slide slide level1 center">
<h1>Part 2 — Three themes</h1>

</section>

<section>
<section id="theme-1-inflation-volatile-food-and-el-niño" class="title-slide slide level1 center">
<h1>Theme 1 — Inflation: volatile food and El Niño</h1>

</section>
<section id="why-focus-on-volatile-food" class="slide level2 m">
<h2>Why focus on volatile food</h2>
<ul>
<li><p>Core inflation is not the problem. At 2.76% it is inside the target band and gives Bank Indonesia room.</p></li>
<li><p>Volatile food is 15.8% of the basket but contributed 0.91 pp of June’s 3.34% — more than a quarter of headline inflation from a sixth of the basket.</p></li>
<li><p>It is also the component that bites hardest on purchasing power: food is a much larger share of the consumption basket for low-income households than for the average.</p></li>
<li><p>The evidence of that bite is already visible: retail sales contracted 4.0% y-on-y in Q2-2026, and the food, beverages and tobacco category contracted 4.1%.</p></li>
<li><p>And unlike core inflation, volatile food is driven by a variable no interest rate can touch: the weather.</p></li>
</ul>
</section>
<section id="el-niño-and-food-prices-move-together" class="slide level2 m">
<h2>El Niño and food prices move together</h2>

<img data-src="fig/elnino_volatile_food.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section id="reading-the-enso-chart" class="slide level2 m">
<h2>Reading the ENSO chart</h2>
<ul>
<li><p>The correlation over the full sample is 0.35 — modest on the contemporaneous reading, but the visual relationship is clear at the peaks: 2015–16, 2023–24, and now.</p></li>
<li><p>The transmission runs through rainfall to harvests to rice, chilli and shallot prices, with a lag of roughly two to three quarters.</p></li>
<li><p>The 2023–24 El Niño coincided with volatile food inflation peaking near 10%.</p></li>
<li><p>We are now entering a larger one.</p></li>
</ul>
</section>
<section id="the-202627-el-niño" class="slide level2 m">
<h2>The 2026–27 El Niño</h2>
<ul>
<li><p>NOAA and BMKG project the <a href="https://setkab.go.id/hadapi-el-nino-godzilla-pemerintah-pastikan-kesiapan-cadangan-pangan-dan-infrastruktur-pertanian-nasional/">current El Niño</a> to be the strongest in roughly 150 years, peaking at the end of 2026 and continuing into early 2027.</p></li>
<li><p>Ramadan and Idulfitri 2027 fall a month earlier than in 2026, which means peak seasonal food demand lands on top of the El Niño peak.</p></li>
<li><p>Q4-2026 therefore faces a simultaneous supply shock and demand surge, into an economy where retail sales are already contracting.</p></li>
</ul>
</section>
<section id="act-early-not-accurately" class="slide level2 m">
<h2>Act early, not accurately</h2>
<p>The policy problem is one of lags, not of forecasting.</p>
<ul>
<li><p>Rice procurement, import licensing and distribution each take months. A decision taken when prices have already moved arrives after the harvest window has closed.</p></li>
<li><p>Government rice reserves and other food reserves must be built before the peak, not during it.</p></li>
<li><p>Distribution, not just stock, is the binding constraint. Price dispersion across provinces during the 2024 episode was larger than the national average increase.</p></li>
<li><p>Social assistance should be pre-positioned for Q4-2026 to protect purchasing power, given that consumption is already softening.</p></li>
</ul>
</section>
<section id="import-if-necessary" class="slide level2 m">
<h2>Import if necessary</h2>
<ul>
<li><p>Import flexibility is the cheapest insurance available, and the most politically expensive to use late.</p></li>
<li><p>The asymmetry is stark: importing rice that turns out not to be needed costs a storage and disposal loss. Not importing rice that turns out to be needed costs a food-price spike, a real-income shock, and a monetary policy dilemma.</p></li>
<li><p>Waiting for confirmation that domestic supply has failed guarantees arriving late, because the shipping and clearance lag is itself two to three months.</p></li>
<li><p>The 2023–24 episode is the natural experiment: the decision to import came after the price had moved, and the import then arrived into a recovering market — the worst of both.</p></li>
</ul>
</section></section>
<section>
<section id="theme-2-fiscal" class="title-slide slide level1 center">
<h1>Theme 2 — Fiscal</h1>

</section>
<section id="apbn-semester-i-2026" class="slide level2 s scrollable">
<h2>APBN Semester I 2026</h2>
<table class="caption-top">
<colgroup>
<col style="width: 21%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>(IDR trillion)</th>
<th style="text-align: right;">2025 budget</th>
<th style="text-align: right;">2025 S-I</th>
<th style="text-align: right;">2026 budget</th>
<th style="text-align: right;">2026 S-I</th>
<th style="text-align: right;">% of budget</th>
<th style="text-align: right;">Growth (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A. Revenue</td>
<td style="text-align: right;">3,005.1</td>
<td style="text-align: right;">1,201.8</td>
<td style="text-align: right;">3,153.6</td>
<td style="text-align: right;">1,459.4</td>
<td style="text-align: right;">46.3</td>
<td style="text-align: right;">21.4</td>
</tr>
<tr class="even">
<td>I. Tax revenue</td>
<td style="text-align: right;">2,490.9</td>
<td style="text-align: right;">978.3</td>
<td style="text-align: right;">2,693.7</td>
<td style="text-align: right;">1,187.8</td>
<td style="text-align: right;">44.1</td>
<td style="text-align: right;">21.4</td>
</tr>
<tr class="odd">
<td>1. Taxes</td>
<td style="text-align: right;">2,189.3</td>
<td style="text-align: right;">831.3</td>
<td style="text-align: right;">2,357.7</td>
<td style="text-align: right;">1,035.7</td>
<td style="text-align: right;">43.9</td>
<td style="text-align: right;">24.6</td>
</tr>
<tr class="even">
<td>2. Customs &amp; excise</td>
<td style="text-align: right;">301.6</td>
<td style="text-align: right;">147.0</td>
<td style="text-align: right;">336.0</td>
<td style="text-align: right;">152.0</td>
<td style="text-align: right;">45.2</td>
<td style="text-align: right;">3.4</td>
</tr>
<tr class="odd">
<td>II. Non-tax revenue</td>
<td style="text-align: right;">513.6</td>
<td style="text-align: right;">222.9</td>
<td style="text-align: right;">459.2</td>
<td style="text-align: right;">271.0</td>
<td style="text-align: right;">59.0</td>
<td style="text-align: right;">21.6</td>
</tr>
<tr class="even">
<td>B. Expenditure</td>
<td style="text-align: right;">3,621.3</td>
<td style="text-align: right;">1,406.0</td>
<td style="text-align: right;">3,842.7</td>
<td style="text-align: right;">1,656.0</td>
<td style="text-align: right;">43.1</td>
<td style="text-align: right;">17.8</td>
</tr>
<tr class="odd">
<td>I. Central government</td>
<td style="text-align: right;">2,701.4</td>
<td style="text-align: right;">1,003.6</td>
<td style="text-align: right;">3,149.7</td>
<td style="text-align: right;">1,298.6</td>
<td style="text-align: right;">41.2</td>
<td style="text-align: right;">29.4</td>
</tr>
<tr class="even">
<td>1. Line ministries (K/L)</td>
<td style="text-align: right;">1,160.1</td>
<td style="text-align: right;">470.5</td>
<td style="text-align: right;">1,510.5</td>
<td style="text-align: right;">658.9</td>
<td style="text-align: right;">43.6</td>
<td style="text-align: right;">40.0</td>
</tr>
<tr class="odd">
<td>2. Non-K/L</td>
<td style="text-align: right;">1,541.4</td>
<td style="text-align: right;">533.0</td>
<td style="text-align: right;">1,639.2</td>
<td style="text-align: right;">639.7</td>
<td style="text-align: right;">39.0</td>
<td style="text-align: right;">20.0</td>
</tr>
<tr class="even">
<td>II. Transfers to regions</td>
<td style="text-align: right;">919.9</td>
<td style="text-align: right;">402.5</td>
<td style="text-align: right;">693.0</td>
<td style="text-align: right;">357.4</td>
<td style="text-align: right;">51.6</td>
<td style="text-align: right;">−11.2</td>
</tr>
<tr class="odd">
<td>C. Primary balance</td>
<td style="text-align: right;">−63.3</td>
<td style="text-align: right;">52.8</td>
<td style="text-align: right;">−89.7</td>
<td style="text-align: right;">85.1</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">61.0</td>
</tr>
<tr class="even">
<td>D. Overall balance</td>
<td style="text-align: right;">−616.2</td>
<td style="text-align: right;">−204.2</td>
<td style="text-align: right;">−689.1</td>
<td style="text-align: right;">−196.5</td>
<td style="text-align: right;">28.5</td>
<td style="text-align: right;">−3.8</td>
</tr>
<tr class="odd">
<td><em>% of GDP</em></td>
<td style="text-align: right;"><em>−2.53</em></td>
<td style="text-align: right;"><em>−0.84</em></td>
<td style="text-align: right;"><em>−2.68</em></td>
<td style="text-align: right;"><em>−0.76</em></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>E. Financing</td>
<td style="text-align: right;">616.2</td>
<td style="text-align: right;">283.6</td>
<td style="text-align: right;">689.1</td>
<td style="text-align: right;">452.0</td>
<td style="text-align: right;">65.6</td>
<td style="text-align: right;">59.4</td>
</tr>
</tbody>
</table>
</section>
<section id="the-state-budget" class="slide level2 m">
<h2>The State Budget</h2>
<ul>
<li><p>The headline is reassuring: deficit 0.76% of GDP, primary balance in surplus at Rp85.1 tn, revenue up 21.4%.</p></li>
<li><p>Revenue growth is narrow. Of the Rp1,035.7 tn of tax receipts, VAT and luxury-goods tax alone contributed Rp380.0 tn, growing 42.2%.</p></li>
<li><p>Subsidy and compensation realised at Rp233.0 tn, already 52.1% of the full-year budget in six months.</p></li>
<li><p>ICP averaged USD 91.87/barrel against the APBN’s USD 70, the rupiah Rp17,197/USD against Rp16,500, and inflation 3.34% against 2.5%.</p></li>
<li><p>Transfers to regions were cut 11.2% — the deficit was protected by squeezing subnational government, which is where capital spending happens.</p></li>
<li><p>Financing was front-loaded: 65.6% of the annual plan in six months, with net debt financing at 57.4% of budget and SBN issuance at 62.7%.</p></li>
</ul>
</section>
<section id="the-interest-bill" class="slide level2 m">
<h2>The interest bill</h2>

<img data-src="fig/fiscal_primary_interest.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section id="reading-the-fiscal-chart" class="slide level2 m">
<h2>Reading the fiscal chart</h2>
<ul>
<li><p>Net interest payments have risen every year but two since 2014, from 1.36% of GDP to a projected 2.43% in 2026 — a 79% increase in the interest burden relative to the economy.</p></li>
<li><p>The primary balance, meanwhile, has been close to zero since 2022. Indonesia is not running large primary deficits.</p></li>
<li><p>That is the whole story: the deficit is increasingly the interest bill, not the programme spending. In 2026 the projected overall deficit of about 3.0% of GDP is roughly 0.6 pp primary deficit plus 2.4 pp interest.</p></li>
<li><p>The debt stock (~40% GDP) is not the issue. The flow is: interest is a first claim on revenue before a rupiah of programme spending.</p></li>
</ul>
</section>
<section id="why-this-constrains-everything-else" class="slide level2 m">
<h2>Why this constrains everything else</h2>
<ul>
<li><p>A rising interest bill with a flat primary balance means the debt ratio climbs even with disciplined programme spending.</p></li>
<li><p>The arithmetic is unforgiving when the effective interest rate exceeds nominal growth. The rupiah averaged Rp17,197/USD against the Rp16,500 assumed, which raises the cost of the foreign-currency share.</p></li>
<li><p>Moody’s and Fitch: interest-to-revenue above 15%, which Fitch already reads at 17%.</p></li>
<li><p>The binding constraint on Indonesia’s fiscal ambition is the interest bill, and the only durable answer is revenue.</p></li>
</ul>
</section></section>
<section>
<section id="theme-3-geoeconomics" class="title-slide slide level1 center">
<h1>Theme 3 — Geoeconomics</h1>

</section>
<section id="geopolitical-risk-is-elevated-and-volatile" class="slide level2 m">
<h2>Geopolitical risk is elevated and volatile</h2>

<img data-src="fig/gpr_annotated.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"><p>Geopolitical Risk index (Caldara &amp; Iacoviello 2022)</p>
</section>
<section id="governments-are-intervening-again" class="slide level2 xs">
<h2>Governments are intervening again</h2>

<img data-src="fig/nipo_trajectory.png" class="quarto-figure quarto-figure-center r-stretch" style="width:90.0%"><p>Number of industrial policy measures per year, distortive versus liberalising, from the <a href="https://globaltradealert.org/reports/new-industrial-policy-observatory-nipo">New Industrial Policy Observatory</a></p>
</section>
<section id="what-is-targeted-and-why" class="slide level2 xs">
<h2>What is targeted, and why</h2>

<img data-src="fig/nipo_sectors_motives.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"><ul>
<li><p>Interventions concentrate on dual-use (70%), advanced technology (46%), low-carbon (39%), medical (35%) and critical minerals (23%) products.</p></li>
<li><p>Stated motives: national security (24%) and supply-chain resilience (14%) — geopolitics, not classical market failure.</p></li>
</ul>
</section>
<section id="trade-blocs-are-re-forming" class="slide level2 m">
<h2>Trade blocs are re-forming</h2>
<p>Gopinath, Gourinchas, Presbitero &amp; Topalova (<em>Journal of International Economics</em>, 2025), gravity estimation on granular bilateral data:</p>
<ul>
<li><p>Since the Ukraine war, trade between the US-centric and China-centric blocs is about 11% lower, and FDI about 12% lower, than flows within the same bloc.</p></li>
<li><p>Historical benchmark: during the Cold War, inter-bloc trade fell by two-thirds relative to intra-bloc. There is a great deal of room left to deteriorate.</p></li>
<li><p>The key difference from the Cold War: non-aligned “connector” countries show no decline — they bridge the two blocs and gain share.</p></li>
<li><p>Indonesia trades heavily with both blocs. Connector status is an asset — and it is measurable.</p></li>
</ul>
</section>
<section id="closing" class="slide level2 m">
<h2>Closing</h2>
<ul>
<li><p>Growth is 5.61%, but its composition is fragile: government consumption, a nickel-processing chain, and food demand financed by the budget. PMI at 47.7 says the forward-looking picture is weaker than the backward-looking one.</p></li>
<li><p>Inflation pressure is not from demand. It is administered prices and volatile food — and the largest El Niño in 150 years peaks in Q4-2026, into an early Ramadan. Act on supply and imports now, not in December.</p></li>
<li><p>The fiscal constraint is the interest bill. Two of three rating agencies have moved to negative outlook on exactly this point.</p></li>
<li><p>Geoeconomics is no longer background. Import concentration is rising, blocs are re-forming, and Indonesia’s connector position is an asset that is quietly eroding.</p></li>
</ul>
</section>
<section id="references" class="slide level2 xs">
<h2>References</h2>
<div class="columns">
<div class="column" style="width:49%;">
<p>BPS. 2024–2026. <em>Pertumbuhan Ekonomi Indonesia</em>, quarterly BRS: No.&nbsp;16/02/Th. XXVII; 17/02/Th. XXVIII; 74/08/Th. XXVIII; 102/11/Th. XXVIII; 18/02/Th. XXIX; 48/05/Th. XXIX.</p>
<p>BPS. 2026. <em>Perkembangan Ekspor dan Impor Indonesia Mei 2026.</em> BRS No.&nbsp;64/07/Th. XXIX, 1 July.</p>
<p>BPS. 2026. <em>Perkembangan Indeks Harga Konsumen Juni 2026.</em> BRS No.&nbsp;61/07/Th. XXIX, 1 July.</p>
<p>BPS. 2026. <em>Pendapatan Nasional Indonesia 2021–2025.</em> Jakarta, 22 June.</p>
<p>BPS. 2026. Static table 908, <em>Inflasi Umum, Inti, Harga Diatur Pemerintah, dan Bergejolak Nasional.</em></p>
<p>Caldara, D. &amp; M. Iacoviello. 2022. Measuring geopolitical risk. <em>American Economic Review</em> 112(4).</p>
<p>CSIS Indonesia. 2026. <em>Strategic Diversification as Indonesia’s Foreign Economic Policy.</em> Jakarta.</p>
<p>Dewan Ekonomi Nasional. 2026. <em>Catatan Perkembangan Ekonomi Terkini</em>, 20 July.</p>
</div><div class="column" style="width:49%;">
<p>EIA. 2026. <em>Europe Brent Spot Price FOB</em>, daily, series DCOILBRENTEU via FRED, Federal Reserve Bank of St.&nbsp;Louis.</p>
<p>Global Trade Alert. 2026. <em>New Industrial Policy Observatory (NIPO)</em>, April.</p>
<p>Gopinath, G., P.-O. Gourinchas, A. F. Presbitero &amp; P. Topalova. 2025. Changing global linkages: A new Cold War? <em>Journal of International Economics</em> 153.</p>
<p>Gupta, K. et al.&nbsp;2026. Prabowonomics: Can Indonesia really grow at 8%? <em>Bulletin of Indonesian Economic Studies</em>, Survey of Recent Developments, April.</p>
<p>Kementerian Keuangan. 2026. <em>APBN KITA — Kinerja dan Fakta</em>, July edition.</p>
<p>Moody’s Ratings, 5 February 2026; Fitch Ratings, 4 March 2026; S&amp;P Global Ratings, 13 July 2026 — Indonesia sovereign rating actions.</p>
<p>OECD. 2026. <em>Economic Outlook No.&nbsp;119.</em> Paris.</p>
</div></div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="kg_toyotatsusho_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="kg_toyotatsusho_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="kg_toyotatsusho_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="kg_toyotatsusho_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="kg_toyotatsusho_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="kg_toyotatsusho_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="kg_toyotatsusho_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="kg_toyotatsusho_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="kg_toyotatsusho_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="kg_toyotatsusho_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="kg_toyotatsusho_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'convex',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>