# Pendahuluan

## Sosial kok belajar matematika dan satistika?

Matematika dan statistika seringkali mendapat reputasi sebagai "ilmunya anak IPA". Memang benar bahwa awalnya, matematika dan statistika paling sering digunakan di bidang ilmu tersebut. Matematika lahir dari kebutuhan manusia untuk mencari penjelasan akan berbagai fenomena. Matematika berfokus kepada bagaimana melakukan perdebatan dan pembuktian secara produktif, serta memformulasikan sebuah teori.

Artinya, matematika dan statistika dapat digunakan juga untuk melakukan formulasi terhadap fenomena yang dipelajari dalam ilmu sosial. Misalnya, matematika dan statistika dapat digunakan untuk menghitung risiko untuk keputusan investasi. Kedua ilmu ini juga dapat digunakan untuk meramalkan berbagai meramalkan berbagai indikator ekonomi.

Bahkan, 
    
- Bahkan, statistika digunakan untuk **"berbohong"**.

    - Pemahaman statistika yang baik dapat membantu.

## Apa itu Statistika?

## APa itu Data?

## Matematika sederhana

Akan diajarin lagi beberapa matematika yang sudah anda kenal di SMU/SMK.

Akan ada notasi.

## Soal


