---
title: "Fungsi dan penerapannya"
subtitle: "Pertemuan 3"
author: "Matematika & Statistika"
format: 
  revealjs:
    theme: [simple,../mytheme.scss]
    chalkboard: true
    incremental: false
    transition: convex
    background-transition: fade
    slide-number: true
---

## Bentuk umum & pengertian

- Fungsi adalah suatu bentuk hubungan matematis yang menyatakan hubungan ketergantungan/dependensi/fungsional antara 2 variabel atau lebih.

- Fungsi dibentuk oleh 3 unsur, yaitu variabel, koefisien, dan konstanta.

$$
Y=f(X)
$$

artinya, variabel $Y$ adalah fungsi dari variabel $X$. Atau, besarnya variabel $Y$ ditentukan oleh besarnya variabel $X$, tapi tidak sebaliknya.

## Pengertian & unsur

- Variabel mencerminkan faktor tertentu. Sementara itu, koefisien dan konstanta adalah angka yang membentuk fungsi, mencerminkan bagaimana 2 variabel saling berhubungan.

    - Konstanta hanya berhubungan $\pm$ dengan variabel, sementara koefisien berhubungan selain itu.
    
- Variabel, seperti namanya, bisa bervariasi, alias berubah-ubah.Variabel sendiri adalah himpunan, sementara koefisien dan konstanta bukan.

## Bentuk khusus/spesifik

- Sebuah fungsi $Y=f(X)$ bisa memiliki bentuk spesifik tertentu. Umumnya bentuk spesifik inilah yang akan kita selesaikan.

- Misalnya, sebuah fungsi $Y=f(X)$ memiliki bentuk spesifik:

$$
Y=a_0+a_1X
$$

- $Y$ dan $X$ adalah variabel, $a_0$ adalah konstanta/intersep, dan $a_1$ adalah koefisien/parameter.

## Fungsi

- $X$ disebut juga dengan variabel eksogen, sementara $Y$ disebut juga variabel endogen.
    
- Eksogen $\rightarrow$ bisa diubah sendiri/independen.

- Endogen tidak bisa. Nilai variabel endogen mengikuti perubahan dari variabel eksogen.
    
- Mengubah $Y$ harus dilakukan dengan mengubah $X$: Kadang $X$ disebut variabel input dan $Y$ variabel output

## Bentuk fungsi

- Fungsi spesifik dapat berbentuk apa saja, selama memetakan $X$ menjadi $Y$.

| Fungsi | Nama |
| --- | --- |
| $Y=a_o+a_1X$ | Fungsi linear |
| $Y=a_0+a_1X+a_2X^2$ | Fungsi kuadratik |
| $Y=a_0+a_1^X$ | Fungsi power/eksponen |
| $Y=\frac{a_1}{X}$ | Fungsi resiprokal |
| $Y=a_0+a_1 \ln X$ | Fungsi logaritma |

## Visualisasi

- Fungsi umumnya divisualisasikan dalam 2 dimensi menggunakan koordinat kartesian.

- Koordinat kartesian merupakan sistem yang dapat memetakan dua buah variabel ke dalam  sebuah bidang yang terdiri dari 2 sumbu: sumbu horizontal/absis/$x$ dan sumbu vertikal/ordinat/$y$.
    - bidang ini disebut juga dengan bidang kartesian.

- Sebuah titik $A$ di bidang kartesian punya koordinat $A=(x,y)$.

## Visualisasi

:::: columns
::: {.column width=47%}

```{r}
#| fig-width: 5
#| fig-height: 5
library(tidyverse)
library(ggh4x)

data2 <- data_frame(label = c("A","B","C","D","E","F"),
                          y = c(4,5,0,-1,-3,5),
                          x = c(5,4,3,0,5,-5),
                          xx= x+0.5)
graph<-ggplot()+theme_classic() +
  theme(panel.background = element_rect(fill = "#f0f1eb",
                                        colour = "#f0f1eb"),
        plot.background = element_rect(fill = "#f0f1eb"),
        legend.key = element_rect(fill = "#f0f1eb",linetype = "blank"),
        legend.background = element_rect(fill="#f0f1eb"))

grafik1 <- graph +
  geom_text(data = data2,
            aes(x = x, y = y+0.4, label = label), parse = TRUE,
            family = "Source Sans Pro", size=4)+
  geom_point(data=data2,
             aes(x=x,y=y),color='black',size=3)+
  labs(x='X',y='Y')+
  coord_axes_inside(labels_inside = TRUE)+
  scale_x_continuous(breaks=seq(-5,5,1))+scale_y_continuous(breaks=seq(-5,5,1))

grafik1
```

:::
::: {.column widht=47% .incremental}

Ada 6 titik di bidang/diagram kartesian ini:

- A=(5,4)
- B=(4,5)
- C=(3,0)
- D=(0,-1)
- E=(5,-3)
- F=(-5,5)

:::
::::