---
title: "Silabus"
subtitle: "ECES905205 \n Analisis Ekonomi Perdagangan dan Industri"
author: "I Made Krisna Yudhana Wisnu Gupta"
date: "18 Agustus 2022"
format:
  pdf:
    documentclass: scrartcl
    papersize: a4paper
  html:
    toc: true
---

```{=tex}
\begin{center}
\rule{5.9in}{0.5pt}
\end{center}
```
## Detil mata kuliah

Pengajar: I Made Krisna Yudhana Wisnu Gupta [(Imed)](https://www.krisna.or.id/#CV)  
e-mail: imade.krisna\@ui.ac.id  
waktu: Setiap senin jam 11.00 WIB  
Ruangan: 306  



## Deskripsi mata kuliah

Kenapa negara saling berdagang? Kenapa ada negara yang berdagang secara bebas, namun ada juga yang memilih untuk cenderung tertutup? Institusi apa yang mengatur jalannya perdagangan? Apa hubungan perdagangan internasional dengan pertumbuhan ekonomi dan industri? Bagaimana keterkaitan antara perdagangan, pertumbuhan dan kesejahteraan? Apakah ekspor yang tinggi disertai dengan rendahnya impor adalah sesuatu yang baik? Pada mata kuliah ini, kita akan mendiskusikan pertanyaan-pertanyaan seperti di atas.

Di tengah kembali maraknya kebijakan industri, baik di Indonesia maupun di dunia internasional, materi tentang pertumbuhan industri juga diberikan, termasuk bagaimana upaya Indonesia untuk kembali mengejar pertumbuhan manufaktur. Konteks tentang Indonesia, yang biasanya jarang ada di buku-buku teks konvensional, juga ditambahkan di mata kuliah ini.

Sayangnya, karena dirasa pentingnya menambahkan materi tentang kebijakan industri dan konteks kebijakan publik di Indonesia, mata kuliah ini terpaksa mengorbankan materi tentang transaksi makro-finansial. Namun demikian, materi tentang *international finance* diajarkan pada mata kuliah lain. Di samping itu, materi tentang neraca pembayaran dan pendapatan nasional tetap diajarkan di mata kuliah ini.

Mata kuliah ini didesain untuk Program Pascasarjana Ilmu Ekonomi (PPIE) Universitas Indonesia. Mata kuliah ini memberikan prinsip dasar menganalisis peran perdagangan internasional dalam mencapai tujuan sebuah negara dalam meningkatkan kesejahteraan warganya dan membangun industri serta ekonomi negaranya. Mata kuliah ini sangat cocok diambil oleh desainer kebijakan publik terkait perdagangan internasional dan kebijakan industri maupun peneliti lembaga riset dan organisasi nirlaba yang bergerak di bidang kebijakan publik.

## Capaian pembelajaran

-   Memahami kenapa perdagangan internasional dan industri perlu dipelajari.

-   Mampu menjelaskan teori perdagangan internasional dengan bahasa yang mudah dipahami.

-   Memahami bentuk-bentuk kebijakan terkait perdagangan internasional dan industrial,, dan konsekuensinya terhadap kesejahteraan.

## Buku dan Materi perkuliahan

### Main textbook \[DS\]:

-   Salvatore, D. (2004). International Economics, 8th ed. (8 ed.). John Wiley & Sons, Inc.

### Papers on industrial policies \[P1\]:

-   Aiginger, K., & Rodrik, D. (2020). Rebirth of Industrial Policy and an Agenda for the Twenty-First Century. Journal of Industry, Competition and Trade, 20(2), 189-207. https://doi.org/10.1007/s10842-019-00322-3

-   Chang, H.-J., & Andreoni, A. (2020). Industrial Policy in the 21st Century. Development and Change, 51(2), 324-351. https://doi.org/https://doi.org/10.1111/dech.12570

-   Cherif, R., & Hasanov, F. (2019). The Return of the Policy That Shall Not Be Named: Principles of Industrial Policy. IMF Working Paper, 19(74).

-   Criscuolo, C., Martin, R., Overman, H. G., & Van Reenen, J. (2019). Some Causal Effects of an Industrial Policy. American Economic Review, 109(1), 48-85. https://doi.org/10.1257/aer.20160034

-   Grabowski, R., & Self, S. (2020). Industrialization and deindustrialization in Indonesia. Asia & the Pacific Policy Studies, 7(1), 95-111.

-   Wim, N. (2010). Industrial Policy. In (Vol. 2010). Helsinki, Finland: UNU-WIDER.

### Papers on Indonesian trade policy context \[P2\]:

-   Basri, M. C., & Patunru, A. A. (2012). How to keep trade policy open: the case of Indonesia. Bulletin of Indonesian Economic Studies, 48(2), 191-208. https://doi.org/10.1080/00074918.2012.694154

-   Gupta, K., Pane, D., & Pasaribu, D. (2022). The Advent of A New Trade Governance After The Omnibus Law: Neraca Komoditas (CIPS Policy Paper, Issue. https://www.cips-indonesia.org/neraca-komoditas-policy-paper

-   Pane, D. D., & Patunru, A. A. (2022). The role of imported inputs in firms' productivity and exports: evidence from Indonesia. Review of World Economics. https://doi.org/10.1007/s10290-022-00476-z

-   Pane, D. D., & Patunru, A. A. (2021). Does Export Experience Improve Firms' Productivity? Evidence from Indonesia. The Journal of Development Studies, 57(12), 2156-2176. https://doi.org/10.1080/00220388.2021.1965126

-   Pangestu, M., Rahardja, S., & Ing, L. Y. (2015). Fifty Years of Trade Policy in Indonesia: New World Trade, Old Treatments. Bulletin of Indonesian Economic Studies, 51(2), 239-261. https://doi.org/10.1080/00074918.2015.1061915

## Prasyarat

Mata kuliah ini mensyaratkan pemahaman makroekonomi dan mikroekonomi yang cukup. Dari sisi mikroekonomi, mahasiswa diasumsikan telah memahami *first* dan *second welfare theorem* serta konsekuensi dari kegagalan pasar (*market failure*) dan *imperfect competition* dalam melakukan analisis ekonomi. Dari sisi makroekonomi, mahasiswa dianggap telah memahami *growth theory* dan memahami konsep *interest rate parity*.

## Ujian

Penguasaan materi mata kuliah ini akan diuji dengan:

-   Ujian Tengah Semester, dengan bobot 30%

-   Ujian Akhir Semester, dengan bobot 50%

-   Tugas membuat report/paper, dengan bobot 20%. Tugas akan diberikan melalui platform online google classroom.

{{< pagebreak >}}

## Sesi

+-----------+---------------------------------------------------------------------------------+--------------+
| Pertemuan | Topik                                                                           | Materi       |
+===========+=================================================================================+==============+
| 1         | -   Pengantar tentang mata kuliah ini                                           | DS bab 1     |
|           | -   Kenapa belajar ekonomi internasional?                                       |              |
+-----------+---------------------------------------------------------------------------------+--------------+
| 2         | -   Absolute advantage, comparative advantage, and ricardian model              | DS bab 2,3   |
+-----------+---------------------------------------------------------------------------------+--------------+
| 3         | -   Standard theory of international trade                                      | DS bab 3,4   |
|           |                                                                                 |              |
|           | -   Analisis partial equilibrium                                                |              |
+-----------+---------------------------------------------------------------------------------+--------------+
| 4         | -   Analisis General Equilibrium                                                | DS bab 4,5   |
|           |                                                                                 |              |
|           | -   Terms of trade                                                              |              |
|           |                                                                                 |              |
|           | -   Hecksher-Ohlin model                                                        |              |
+-----------+---------------------------------------------------------------------------------+--------------+
| 5         | -   Skala ekonomis dan kompetisi tidak sempurna dalam perdagangan internasional | DS bab 6     |
+-----------+---------------------------------------------------------------------------------+--------------+
| 6         | -   Perdagangan dan pertumbuhan ekonomi                                         | DS bab 7     |
+-----------+---------------------------------------------------------------------------------+--------------+
| 7         | -   Kebijakan perdagangan: tarif                                                | DS bab 8     |
+-----------+---------------------------------------------------------------------------------+--------------+
| \-        | Midterm exam                                                                    | \-           |
+-----------+---------------------------------------------------------------------------------+--------------+
| 8         | -   Kebijakan perdagangan: non-tarif                                            | DS Bab 9, P2 |
+-----------+---------------------------------------------------------------------------------+--------------+
| 9         | -   Free Trade Agreements                                                       | DS bab 10    |
+-----------+---------------------------------------------------------------------------------+--------------+
| 10        | -   Perusahaan dalam perdagangan internasional                                  | DS bab 12    |
|           |                                                                                 |              |
|           | -   Global Value Chain                                                          |              |
+-----------+---------------------------------------------------------------------------------+--------------+
| 11        | -   Perdagangan internasional dan negara berkembang                             | DS bab 11    |
+-----------+---------------------------------------------------------------------------------+--------------+
| 12        | -   Kebijakan industrial                                                        | P1           |
+-----------+---------------------------------------------------------------------------------+--------------+
| 13        | -   Pendapatan nasional dan neraca pembayaran                                   | DS bab 13    |
+-----------+---------------------------------------------------------------------------------+--------------+
| 14        | -   Konteks Indonesia dalam perdagangan internasional                           | P2           |
+-----------+---------------------------------------------------------------------------------+--------------+
| \-        | Final exam                                                                      | \-           |
+-----------+---------------------------------------------------------------------------------+--------------+
