---
title: "Membuat kerangka penelitian"
subtitle: "Pertemuan 8"
author: "Metodologi penelitian"
format: 
  revealjs:
    theme: [simple,../mytheme.scss]
    chalkboard: true
    transition: convex
    background-transition: fade
    slide-number: true
    incremental: false
---

## What's next

- Kita akan fokus di 7 pertemuan ke depan mempelajari bagaimana membuat penelitian yang bagus.

- Kita akan mulai dengan kerangka penelitian, kemudian membahas tinjauan literatur, menulis metodologi, analisis/pembahasan, dan kesimpulan.

- Juga mempelajari metode-metode yang bisa dipilih, serta alat-alat yang akan berguna seperti Zotero dan Github.

## TA Penelitian di APP

- Format TA di APP bisa berupa laporan kerja praktik, analisis, dan penelitian.

- Penelitian paling jarang dilakukan (biasanya dikira susah padahal ~iya~ bisa dipelajari).

- Keuntungan penelitian:

    - bisa magang di mana saja
    
    - data sekunder (tinggal pakai)
    
## Tugas

- Tugas anda adalah membuat mini-TA penelitian.

- Fungsi tugas ini untuk memfamiliarkan anda dengan format TA penelitian.

- Gunakan ilmu yang akan dipelajari di 7 pertemuan ke depan untuk membuat tugas.

- Tugas akan dikumpulkan di H-1 sebelum UAS, tapi bisa dicicil dari sekarang.

- Lebih lanjut bisa dilihat di [sini](https://krisna.or.id/courses/metopel/tugas/)

## Susunan/outline penelitian {.m}

- TA penelitian di APP terdiri dari beberapa bagian.

- Bagian Awal:

    - Halaman Judul (dan sub judul) ;
    
    - Abstrak/Ringkasan;
    
    - Daftar Isi;
    
    - Daftar Tabel (jika ada)
    
    - Daftar Gambar (jika ada);
    
    - Daftar Grafik (jika ada);
    
    - Daftar Diagram (jika ada); dan
    
    - Daftar Lampiran (jika ada)

## Outline {.m}

- Bagian Inti:
    
    - Pendahuluan;

    - Studi Pustaka;

    - Metode Penelitian/Metodologi;

    - Pembahasan;

    - Kesimpulan

- Bagian Akhir:

    - Daftar Pustaka dan lampiran
    
- Outline ini bentuk standar dalam penyusunan tulisan ilmiah (laporan penelitian, jurnal ilmiah). Dalam penyusunan tugas dalam matkul ini akan menggunakan versi ringkas yaitu bagian inti ditambah dengan daftar Pustaka/referensi saja.

## Bab 1 Pendahuluan {.m}

- **1.1 Latar Belakang** berisi tentang pentingnya topik yang diangkat dalam laporan.

- Motivasi itu penting. Misalnya jika anda memeriksa hubungan antara nilai tukar dan harga CPO, jelaskan di sini kenapa ini penting.

- dapat menggunakan metode identifikasi masalah (fishbone diagram, 5W1H).

- Jika perlu, jelaskan juga tentang konteks tentang penelitian ini. Kenapa penting di Indo tapi ga penting2 amat di negara lain, misalnya.

- di TA, company profile jg taruh sini.

## Bab I Pendahuluan {.m}

- **1.2 Batasan Permasalahan/Ruang Lingkup** menguraikan batasan ruang lingkup bahasan permasalahan pada laporan, dapat berupa batasan waktu maupun topik yang dibahas. Misalnya, penelitian ini mencakup tahun 2001 - 2019, negara yang dipilih adalah 10 negara terbesar, HS yg dipilih, dst.

- **1.3 Rumusan Masalah** menuliskan poin-poin permasalahan apa saja yang akan dibahas dalam laporan. Dapat juga merumuskan hipotesis penelitian. Misalnya, penelitian ini bermaksud melihat tren ekspor barang X.

- **1.4 Tujuan dan Manfaat Penelitian** merupakan jawaban yang akan dicapai dari pembahasan laporan, biasanya dirumuskan dari poin-poin masalah yang telah dijabarkan sebelumnya. Misalnya, mengetahui tren barang X berguna utk perusahaan di bidang X.

## Bab II Studi Pustaka

- Hasil bacaan oleh penulis dari berbagai sumber sesuai dengan topik yang diteliti untuk menghasilkan ide/analisis baru yang dipresentasikan dalam sebuah karya ilmiah. 

- Studi pustaka harus mencakup setidaknya literatur di hubungan variabel yang dipilih (boleh beda konteks), dan metode yang digunakan.

- Jika penelitian anda punya konteks / aturan pemerintah tertentu, maka konteks ini juga perlu dibahas di sini.

- Untuk TA, sebaiknya gunakan setidaknya 3 buku yang terbit 10 tahun terakhir dan jurnal yang terbit 5 tahun terakhir. Utk UAS bebas.

## Bab III Metode Penelitian {.m}

- Bab ini berisikan penjelasan mengenai kerangka pemecahan permasalahan yang ditemui.

- **3.1. Data** Berisikan data yang digunakan, sumber dan metode pengumpulan data yang akan digunakan untuk melakukan analisis dalam laporan.

- **3.2. Metode Analisis** Berisikan metode pengolahan data yang digunakan dalam menyelesaikan permasalahan teknis/operasional yang ditemui, baik secara kualitatif maupun kuantitatif. Pada bagian ini dijelaskan model yang digunakan serta alat bantu dalam pengolahan data.

## Bab IV Pembahasan {.m}

- Bab ini menyajikan penerapan metode yang telah dituangkan pada bab 3 dan hasilnya. 

- Selanjutnya bab ini memaparkan temuan-temuan, analisis dan penjelasan atas temuan tersebut, dan bukti-bukti pendukung penjelasan tersebut.

- **4.1 Pembahasan Masalah** menampilkan data (deskripsi, sumber, kelemahan dan kelebihan) dan visualisasi data yang telah dikumpulkan.

- **4.2 Analisis Masalah** berisi penerapan metode dan pembahasan temuan, serta penjelasan atas temuan tersebut. Hasil dari pembahasan didasari teori yang telah dijelaskan pada bab II dan dapat dikaitkan dengan hasil temuan terdahulu.

## Bab V Kesimpulan

- Bagian ini berisi jawaban dari permasalahan dan tujuan yang diajukan pada laporan, yang diperoleh dari hasil pembahasan dan usulan perbaikan. 

- Saran merupakan tindak lanjut dari kesimpulan, berupa anjuran atau rekomendasi yang disampaikan secara ringkas dan dapat diimplementasikan

- Tidak boleh memberi informasi baru di bab kesimpulan. Semua informasi yang ada di bab ini harus berasal dari bab I sampai bab IV. Jika ada informasi baru, sebaiknya ditaruh di bab sebelumnya.

## Daftar Pustaka/Referensi

- Dalam penulisan daftar pustaka tugas akhir Politeknik APP Jakarta menggunakan format American Psychological Association (APA) 7, bisa menggunakan Zotero.

- Berpeganglah pada pedoman TA Poltek APP jakarta.

- Ada banyak resource yang bisa dipakai untuk APA7, misalnya [ini](https://www.griffith.edu.au/library/study/referencing/apa-7).

- Zotero / Mendeley / sejenisnya akan sangat mempermudah.

## Tips (Tugas dan TA)

- Mulai aja dari isu-isu yang anda tertarik. Tapi kalau bingung, tinggal liat WDI/BPS/SEKI lalu cari variabel yang menurut anda menarik.

- kalo anda mau bikin penelitian TA yg terkait tempat magang, tanya ke bos anda di tempat magang apa isu yg menarik.

- Rajin-rajin bertanya ke pembimbing. Kunci sukses TA adalah rajin bimbingan.

- Diingatkan kembali, apapun bentuk TA anda, **ujian komprehensif** mempunyai bobot 50% di nilai akhir anda.