---
title: "Literature Review"
subtitle: "Pertemuan 13"
author: "Metodologi penelitian"
format: 
  revealjs:
    theme: [simple,../mytheme.scss]
    chalkboard: true
    transition: convex
    background-transition: fade
    slide-number: true
    incremental: false
---

## Tentang hari ini 👀

- Tips and trick
- Some tools
- diskusi

Tips yang ada di sini benar untuk penelitian secara umum. Di APP mungkin sedikit lebih sederhana ketimbang beberapa poin seperti mencari gap.

## Literature review?

- Peneliti pemula seringkali bingung bagaimana memulai tinjauan literatur

- Sebenarnya, tinjauan literatur (dan *referencing*) adalah *skill* yang kita perlukan untuk semua jenis pekerjaan!

*Literature review is actually an investigation!*

---

## Untuk menulis 10 ribu kata, anda harus membaca 100 ribu kata! {.m}

::: {.incremental}

$$\max_{B,T,S} \{f(B,T,S): B+T+S \leq 24\}$$

$B>T>S$

:::

Baca $\Rightarrow$ Tulis $\Rightarrow$ Speak

JANGAN KEBALIK!

hehe 😊

## Kenapa melakukan tinjauan literatur {.m}

- Kita tidak bisa meneliti sesuatu yang kita tidak tau!
  - mendapatkan konteks
  - metode termutakhir
  - mencari *gap* di literatur: metode / konteks
  
- Meyakinkan pembaca bahwa riset kita <ins>relevan</ins>:
  - terupdate
  - penting

- Bonus: membantu mengarahkan yang baru mau terjun ke bidang kita!

## Beberapa kesalahan pemula {.m}

| Problem | Komentar |
| ------- | -------- |
| Kurang terorganisir | fokus ke isu, bukan paper. Gunakan mindmap dapat membantu |
| Kurang relevan | Seminal paper biasanya jadul. Penting, tapi fokus ke yang lebih baru |
| Kurang kritis | Ingat, anda bukan <ins>hanya</ins> merangkum, tapi juga mencari *gap* |
| Takut salah | Mahasiswa adalah tempatnya salah. Yang penting kita belajar dari situ |

## Mulai dari mana?

- Kata kunci-nya adalah relevan!
  - meneliti tentang Kazakhstan bagi audience Indonesia mungkin kurang rame
  
- Paling mudah adalah mulai dari isu yang relevan dengan kita:
  - Misal, sesuatu yang kita sering dengar (misalnya korupsi daging sapi, omnibus law)
  - Bisa juga yang relevan dengan kerjaan kita

- Bisa juga mulai dari metode.

## Mulai dari mana?

- Sebagian besar pertanyaan di bidang ilmu ekonomi adalah tentang hubungan dua variabel:

> Does X causes Y?

$$ Y = X\beta + \varepsilon $$

Kita bisa mulai mencari menggunakan kata kunci Y atau X, atau keduanya.

---

## Mulai dari mana?

- beberapa pertanyaan yang bisa dijawab, misalnya:

  - $Y \Rightarrow X$ atau $X \Rightarrow Y$?  
  - bagaimana dengan $Z$?  
  - di Amerika, $X \Rightarrow Y$. Bagaimana dengan di Indonesia?
  - apa lagi kira-kira?

## Tabel dapat membantu proses berpikir kita {.s}

| Author | Y | X | sign | context | method |
| ------ | - | - | ---- | ------- | ------ |
| Amiti & Konings 2007 | TFP | input tariff | + | Indonesia, firm level | levpet, gravity |
| Kee, Nicita, Olarreaga 2009 | import val | NTM count | + | global | cross-section gravity |
| Fugazza, Olarreaga, Ugarte 2017 | export val | NTM count | +,- | Peru | gravity, firm size |
| Cadot et al 2015 | export val | NTM count, Reg. dist. | + | global | gravity cross-section |

> Contoh di atas adalah pencarian yang berfokus pada $X$: Bagaimana Non-Tariff Measures (NTMs) mempengaruhi perdagangan dan produktivitas (dan lainnya kalau ada)

## Diisi juga kontribusi atau gap {.s}

| Author | + | - |
| ------ | - | - | 
| Amiti & Konings 2007 | Jurnal AER, konteks Indonesia, firm level, TFP | Tidak ada NTM |
| Kee, Nicita, Olarreaga 2009 | Seminal utk AVE | Terlalu global dan makro |
| Fugazza, Olarreaga, Ugarte 2017 | heterogenous firm, firm level | konteks Peru, export may not be best measure, no PPML |
| Cadot et al 2015 | Seminal NTM, konsep *regulatory distance* | Cross section, terlalu makro |

> Saya dapat berkontribusi di konteks Indonesia, firm level dengan TFP. Trade policy measures adalah tariff dan NTMs. Measures untuk firm level export dapat dipakai untuk *robustness*. Data ada, metode ada, export lebih baik dimodelkan dengan PPML. Sip!

## Mulai dari mana?

- Literaturnya literatur: akan ada *author(s)* yang disebut berkali-kali oleh literatur yang anda sudah temukan.

  - Trade context: Krugman, Melitz, Grossman & Helpman, Bernard, Kee, Cadot

  - General equilibrium: Hertel, Horridge, McKibbin, Dixon, Costinot

  - Indonesian context: Sjoholm, Hill, Aswicahyono, Patunru, Sparrow

- Bisa juga tanya dosen

## Mulai dari mana?

- *report* lembaga penting seperti IMF, World Bank dan Kementerian/Lembaga.

- *textbook* dan referensinya.

- Google (scholar) sangat berguna karena repositori-nya sangat luas. Namun harus agak berhati-hati. Pastikan yang anda sitasi adalah yang *peer-reviewed*.

- Mulai dari wikipedia jika anda bener-bener newb juga boleh. Jangan lupa lihat sitasi yang ada di Wikipedia, jangan Wikipedianya langsung ya.

- Jika ragu, tanya pembimbing anda.

## Final tips

- Tinjauan literatur sangat penting dilakukan meskipun skripsi anda tidak punya bab berjudul "tinjauan literatur"

- Baca bab *literature review* orang lain, dan coba bedah strukturnya

- Minta tolong orang lain membaca bab *literature review* anda (kalau ada)

- tanya dosen / pembimbing / teman anda yang pintar

## butuh berapa referensi?

- *Rule of thumb* saya: minimal 10 referensi utama di 5 tahun terakhir, tentang metode.

- Dari 10 itu, ambil referensi mereka yang paling relevan (cek abstrak).

- Gunakan referensi lain untuk *setting* konteks.
  - Misalnya, saya pake [Patunru dan Rahardja (2015)](https://think-asia.org/handle/11540/6410) untuk pembukaan saja, bukan metodenya.

- Tapi jumlahnya kira-kira aja. Sebaiknya tanya pembimbing.

## Mindmap {.m}

- Beberapa mindmap bisa digunakan, tapi favorit saya adalah connected papers (https://www.connectedpapers.com/)

- connected papers akan menunjukkan interkoneksi antar artikel. Cara cepat untuk mengetahui jaringan sitasi di sebuah isu.

- ukuran node menunjukkan besarnya sitasi, sementara ketebalan warna menunjukan keterbaruan.

- contohnya ketika kita mencari [Melitz 2003](https://www.connectedpapers.com/search?q=melitz%202003)

- Menariknya, koneksi berbasis isu juga ditampilkan. Lebih keliatan jika kita cari artikel yang belum ada sitasinya. Misalnya [krisna gupta](https://www.connectedpapers.com/search?q=krisna%20gupta)

## Menggunakan *reference manager*

- *Reference manager* adalah piranti lunak yang sangat membantu dalam me-*manage* daftar pustaka kita.

- Dengan *Reference manager*, kita bisa dengan cepat melakukan sitasi dan membuat daftar pustaka dengan format yang kita inginkan.

- *Reference manager* juga membantu kita mengelompokan dan memasang tag di referensi-referensi kita.

- Zotero dan Mendeley termasuk *software* gratisan yang paling terkenal. Google Scholar Library juga layak coba

## Menggunakan google scholar

gunakan AND atau & untuk irisan, dan OR untuk *union*

```python
Indonesia AND Australia # will show only Indonesia & AUstralia included
```
```python
Indonesia OR Australia # will show results also when only one of them is present
```

## Menggunakan google scholar

gunakan tanda petik untuk mencari satu rangkaian kata

```python
"the case of indonesia"
```
gunakan author:"nama-author" untuk mencari karya peneliti tersebut

```python
author:"Costinot"
```

gunakan `..` untuk memberi interval di pencarian kita

```python
Indonesia AND Trade 2010..2018
```
## Menggunakan google scholar

- pakai tanda bintang untuk mencari lanjutan. Misalnya, `indust*` akan mencarikan `industri`, `industry`, `industrial` dan `industrialisasi`.

- gunakan tanda tanya untuk mencari produk yang ejaannya berbeda. Misalnya, `labo?r` akan menemukan sesuatu yang ada kata `labor` dan `labour`

- Trik asterisk juga bisa digunakan untuk ejaan berbeda, misalnya `globali*` akan menemukan `globalization` dan `globalisation`

- Selengkapnya bisa google `wildcard search`

## Kesimpulan

- Tinjauan literatur sejatinya adalah investigasi

- Kata kuncinya adalah relevan!

- Gunakan semua resources yang ada!

- Jika bingung, tanya pembimbing

## References
- Lange, Cheryl. (N.D.). [Writing your literature review](https://www.student.uwa.edu.au/__data/assets/pdf_file/0011/2521658/3_Write_literature_review_sem1.pdf?utm_content=bufferbbda3&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer). *Studysmarter research series*. The University of Western Australia.

- Rowland, DR. (N.D.). [Reviewing the literature: a short guide for research students](https://my.uq.edu.au/files/11020/guide-literature-review-research-students.pdf?utm_content=buffer0f227&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer). The University of Queensland.