<!DOCTYPE html>
<html lang="en"><head>
<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/tabby.min.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="I Made Krisna Gupta">
  <title>Exchange Rates &amp; FX Market</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/theme/quarto-6a0936f214d018485b9e1b578c23d634.css">
  <link href="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Exchange Rates &amp; FX Market</h1>
  <p class="subtitle">ECES905205 pertemuan 11</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
I Made Krisna Gupta 
</div>
</div>
</div>

  <p class="date">Invalid Date</p>
</section>
<section id="recap-todays-plan" class="slide level2 s">
<h2>Recap &amp; today’s plan</h2>
<ul>
<li><p>Pekan lalu: BoP, current account, national income — semua dalam “uang”, tapi belum bahas bagaimana <em>harga</em> uang antar negara terbentuk.</p></li>
<li><p>Hari ini: KOM Ch.14 (FX market) + short-run Ch.15 (money &amp; FX).</p></li>
<li><p>Roadmap: definisi nilai tukar → struktur pasar FX (spot, forward, swap, options) → returns, UIP, carry trade → forward &amp; CIP → money basics &amp; monetary policy ke FX.</p></li>
</ul>
</section>
<section id="what-is-an-exchange-rate" class="slide level2 s">
<h2>What is an exchange rate?</h2>
<ul>
<li><p>Nilai tukar <span class="math inline">\(E\)</span> = harga satu mata uang dalam mata uang lain.</p></li>
<li><p>Konvensi quotation ada dua:</p>
<ul>
<li><p><strong>Direct (Indonesian convention)</strong>: Rp 16.400 per 1 USD.</p></li>
<li><p><strong>Indirect</strong>: USD 0,0000610 per 1 Rp.</p></li>
</ul></li>
<li><p>Sepanjang kuliah kita pakai <span class="math inline">\(E = Rp/USD\)</span>. Jadi <span class="math inline">\(E=16.400\)</span> berarti 1 USD = Rp 16.400.</p></li>
<li><p>Naik = rupiah depresiasi. Turun = rupiah apresiasi. <strong>Ini bagian yang sering bikin bingung.</strong></p></li>
</ul>
</section>
<section id="appreciation-vs-depreciation" class="slide level2 s">
<h2>Appreciation vs Depreciation</h2>
<ul>
<li><p>Misal <span class="math inline">\(E\)</span> bergerak dari 16.400 → 16.800.</p>
<ul>
<li><p>Untuk membeli 1 USD, perlu rupiah lebih banyak ⇒ <strong>rupiah depresiasi</strong> (terhadap dollar).</p></li>
<li><p>Equivalently, dollar <strong>appreciates</strong> terhadap rupiah.</p></li>
</ul></li>
<li><p>Persentase: <span class="math inline">\(\Delta E / E = (16.800-16.400)/16.400 \approx 2{,}44\%\)</span> depresiasi.</p></li>
<li><p>Direction-of-quote trap:</p>
<ul>
<li><p>“Kurs naik” di media biasanya berarti <strong>rupiah melemah</strong> (karena yang diquote <span class="math inline">\(E=Rp/USD\)</span>).</p></li>
<li><p>Kalau ditulis <span class="math inline">\(E=USD/Rp\)</span> (jarang), “naik” justru artinya rupiah menguat.</p></li>
</ul></li>
<li><p>Selalu tanya: yang naik itu <strong>angka quotation</strong>, bukan “nilai rupiah” sendiri.</p></li>
</ul>
</section>
<section id="er-relative-prices" class="slide level2 s">
<h2>ER &amp; relative prices</h2>
<ul>
<li><p>Nilai tukar menghubungkan harga domestik dengan harga luar negeri.</p></li>
<li><p><strong>Pertamina</strong> (impor crude): Brent USD 80/barel. Pada <span class="math inline">\(E=16.400\)</span> → Rp 1,31 jt/barel. Jika <span class="math inline">\(E=17.000\)</span> → Rp 1,36 jt/barel.</p></li>
<li><p><strong>Sritex</strong> (eksportir tekstil): jual baju USD 10. Pada <span class="math inline">\(E=16.400\)</span> → Rp 164.000. Jika <span class="math inline">\(E=17.000\)</span> → Rp 170.000.</p></li>
<li><p><strong>Eksportir senang ketika rupiah depresiasi, importir tidak.</strong></p></li>
</ul>
</section>
<section id="who-wins-who-loses" class="slide level2 s">
<h2>Who wins, who loses?</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Rupiah depresiasi (<span class="math inline">\(E \uparrow\)</span>)</th>
<th>Rupiah apresiasi (<span class="math inline">\(E \downarrow\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Eksportir (Sritex, kopi, nikel)</td>
<td>+ revenue Rp</td>
<td>− revenue Rp</td>
</tr>
<tr class="even">
<td>Importir (BBM, pangan)</td>
<td>− cost naik</td>
<td>+ cost turun</td>
</tr>
<tr class="odd">
<td>Konsumen barang impor (iPhone, Avanza)</td>
<td>− mahal</td>
<td>+ murah</td>
</tr>
<tr class="even">
<td>Pemegang utang USD</td>
<td>− beban naik</td>
<td>+ beban turun</td>
</tr>
<tr class="odd">
<td>Turis asing ke Bali</td>
<td>+ Indonesia murah</td>
<td>− Indonesia mahal</td>
</tr>
</tbody>
</table>
<ul>
<li>Nilai tukar bukan “selalu lebih baik kalau kuat” — tergantung stakeholder.</li>
</ul>
</section>
<section id="usdidr-history" class="slide level2">
<h2>USD/IDR history</h2>

<img data-src="index_files/figure-revealjs/unnamed-chunk-1-1.png" width="960" class="r-stretch"></section>
<section id="real-effective-er" class="slide level2 s">
<h2>Real &amp; effective ER</h2>
<ul>
<li><strong>Real exchange rate</strong> <span class="math inline">\(q\)</span>:</li>
</ul>
<p><span class="math display">\[
q = \frac{E \cdot P^*}{P}
\]</span></p>
<pre><code>di mana $P$ = harga domestik, $P^*$ = harga luar negeri, $E$ = nominal ER (Rp/USD).</code></pre>
<ul>
<li><p><span class="math inline">\(q\)</span> menunjukkan daya beli relatif — bukan sekadar nominal.</p></li>
<li><p><strong>Effective exchange rate</strong> (NEER/REER): rata-rata tertimbang nilai tukar terhadap <em>basket</em> partner dagang.</p>
<ul>
<li><p>BI mempublikasikan NEER dan REER bulanan.</p></li>
<li><p>REER yang stabil ≠ nominal rate stabil; bisa nominal melemah tapi inflasi domestik tinggi → REER tetap.</p></li>
</ul></li>
<li><p>Pembahasan formal PPP dan REER pekan depan (Ch.15 long-run).</p></li>
</ul>
</section>
<section id="who-trades-fx" class="slide level2 s">
<h2>Who trades FX?</h2>
<ul>
<li><p>Pasar FX adalah <strong>OTC</strong> (over-the-counter), bukan bursa.</p></li>
<li><p>Pelaku utama:</p>
<ul>
<li><p><strong>Commercial banks</strong> — market makers (BCA, Mandiri, BNI, BRI + global).</p></li>
<li><p><strong>Non-bank FIs</strong> — hedge funds, asset managers, asuransi.</p></li>
<li><p><strong>Korporasi</strong> — eksportir/importir hedging (Pertamina, Indofood, Astra).</p></li>
<li><p><strong>Bank Indonesia</strong> — intervensi untuk stabilisasi.</p></li>
<li><p><strong>Retail</strong> — kecil tapi tumbuh.</p></li>
</ul></li>
<li><p>24 jam: Sydney → Tokyo → Singapore → London → New York.</p></li>
<li><p>BIS Triennial 2022: turnover global FX ≈ USD 7,5 T/hari.</p></li>
<li><p>Hub utama: London 38%, New York 19%, Singapore 9%, Hong Kong 7%, Tokyo 4%.</p></li>
</ul>
</section>
<section id="spot-forward-swap" class="slide level2">
<h2>Spot, forward, swap</h2>
<ul>
<li><p><strong>Spot</strong>: pengiriman T+2. Quote yang muncul di Bloomberg/Yahoo.</p></li>
<li><p><strong>Forward</strong>: <a href="https://www.bca.co.id/id/informasi/kurs-forward">kunci kurs</a> <em>sekarang</em> untuk pengiriman tanggal masa depan. Tenor 1m, 3m, 6m, 12m.</p></li>
<li><p><strong>FX swap</strong>: spot leg + forward leg. Equivalent dengan <em>collateralized lending</em> antar mata uang.</p></li>
<li><p>Mengapa forward exists? Importir/eksportir butuh kepastian cashflow; bank butuh tools manage posisi.</p></li>
</ul>
</section>
<section id="fx-derivatives" class="slide level2">
<h2>FX derivatives</h2>
<ul>
<li><p><strong>FX futures</strong>: forward terstandarisasi di bursa (CME). Marked-to-market harian. Volume IDR kecil.</p></li>
<li><p><strong>FX options</strong>:</p>
<ul>
<li><p><strong>Call USD</strong> = hak (bukan kewajiban) beli USD pada strike.</p></li>
<li><p><strong>Put USD</strong> = hak jual USD.</p></li>
<li><p>Importir beli call USD = asuransi terhadap depresiasi rupiah.</p></li>
</ul></li>
</ul>
</section>
<section id="arbitrage-cross-rates" class="slide level2">
<h2>Arbitrage &amp; cross rates</h2>
<ul>
<li><p>Jika <span class="math inline">\(E_{Rp/USD}=16.400\)</span> dan <span class="math inline">\(E_{JPY/USD}=150\)</span>, maka <span class="math inline">\(E_{Rp/JPY} \approx 109{,}3\)</span>.</p></li>
<li><p>Triangular arbitrage: jika quoted cross rate ≠ implied cross rate → trader arbitrase sampai gap tertutup.</p></li>
<li><p>Di deep market, cross rates ≈ implied. <strong>Tidak ada free lunch</strong> di pasangan major.</p></li>
<li><p>Bank-bank market maker menjaga kondisi <em>no-arbitrage</em> secara terus-menerus.</p></li>
</ul>
</section>
<section id="asset-approach-to-fx" class="slide level2">
<h2>Asset approach to FX</h2>
<ul>
<li><p>KOM: <strong>nilai tukar adalah harga aset.</strong></p></li>
<li><p>Yang dipegang trader/investor adalah <em>deposit</em> dalam berbagai mata uang.</p></li>
<li><p>Yang menentukan equilibrium adalah <strong>expected return</strong> dari tiap deposit, bukan flow ekspor-impor saja.</p></li>
<li><p>Implikasi: nilai tukar bisa sangat volatile dan <em>overshoot</em> fundamentalnya.</p></li>
</ul>
</section>
<section id="returns-on-deposits" class="slide level2 s">
<h2>Returns on deposits</h2>
<ul>
<li><p>Dua deposit 1-tahun:</p>
<ul>
<li><p>IDR deposit: bunga <span class="math inline">\(R\)</span> (BI 7DRR ≈ 5,75%).</p></li>
<li><p>USD deposit: bunga <span class="math inline">\(R^*\)</span> (Fed Funds ≈ 4,5%).</p></li>
</ul></li>
<li><p>Return diukur dalam <strong>rupiah</strong>:</p>
<ul>
<li><p>IDR deposit: <span class="math inline">\(1 + R\)</span>.</p></li>
<li><p>USD deposit: <span class="math inline">\(\frac{E^e}{E}(1 + R^*)\)</span> — beli USD, tabung, jual di <span class="math inline">\(E^e\)</span> tahun depan.</p></li>
</ul></li>
<li><p>Mana lebih besar? Tergantung <strong>expected appreciation/depreciation rupiah</strong>.</p></li>
</ul>
</section>
<section id="expected-appreciation" class="slide level2 s">
<h2>Expected appreciation</h2>
<ul>
<li>Definisi: rate of depreciation rupiah yang diekspektasikan:</li>
</ul>
<p><span class="math display">\[
\frac{E^e - E}{E}
\]</span></p>
<pre><code>di mana $E^e$ = ekspektasi nilai tukar masa depan, $E$ = nilai tukar saat ini.</code></pre>
<ul>
<li><p>Misal <span class="math inline">\(E=16.400\)</span>, <span class="math inline">\(E^e=16.800\)</span>. Maka ekspektasi depresiasi <span class="math inline">\(\approx 2{,}44\%\)</span>.</p></li>
<li><p>Jika rupiah <em>appreciate</em> (expected): <span class="math inline">\(E^e &lt; E\)</span>, angka ini negatif.</p></li>
<li><p>Note konvensi: ini adalah “expected depreciation rupiah” / “expected appreciation dollar” — karena <span class="math inline">\(E=Rp/USD\)</span>.</p></li>
</ul>
</section>
<section id="expected-return-usd-vs-idr" class="slide level2 s">
<h2>Expected return: USD vs IDR</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Approximation (orde-1):</p>
<p><span class="math display">\[
R^*_{\text{in Rp}} \approx R^* + \frac{E^e - E}{E}
\]</span></p>
<p>Investor bandingkan:</p>
<ul>
<li><p>IDR: <span class="math inline">\(R\)</span></p></li>
<li><p>USD (dalam Rp): <span class="math inline">\(R^* + (E^e-E)/E\)</span></p></li>
</ul>
<p>Selisih:</p>
<p><span class="math display">\[
R - R^* - \frac{E^e - E}{E}
\]</span></p>
</div><div class="column" style="width:45%;">
<p><strong>Intuisi</strong>:</p>
<ul>
<li><p><span class="math inline">\(R \uparrow\)</span> → tarik investor ke IDR.</p></li>
<li><p><span class="math inline">\(R^* \uparrow\)</span> → tarik ke USD.</p></li>
<li><p><span class="math inline">\(E^e \uparrow\)</span> → simpan USD (USD akan apresiasi).</p></li>
</ul>
<p>Investor neutral ketika selisih = 0.</p>
</div></div>
</section>
<section id="numerical-example" class="slide level2 s">
<h2>Numerical example</h2>
<ul>
<li><p>Data: <span class="math inline">\(R = 5{,}75\%\)</span>, <span class="math inline">\(R^* = 4{,}50\%\)</span>, <span class="math inline">\(E = 16.400\)</span>, <span class="math inline">\(E^e = 16.800\)</span>.</p></li>
<li><p>Expected USD return (dalam Rp):</p></li>
</ul>
<p><span class="math display">\[
R^* + \frac{E^e - E}{E} = 4{,}50\% + 2{,}44\% = 6{,}94\%
\]</span></p>
<ul>
<li>IDR return: <span class="math inline">\(5{,}75\%\)</span>. USD deposit lebih menarik → tekanan beli USD → <span class="math inline">\(E\)</span> naik (rupiah depresiasi) sampai equilibrium.</li>
</ul>
</section>
<section id="fx-equilibrium-uip" class="slide level2 s">
<h2>FX equilibrium: UIP</h2>
<ul>
<li><strong>Uncovered Interest Parity</strong> (UIP):</li>
</ul>
<p><span class="math display">\[
R = R^* + \frac{E^e - E}{E}
\]</span></p>
<ul>
<li><p>Di equilibrium, return ekspektasi antar deposit (dalam mata uang sama) harus <em>sama</em>.</p></li>
<li><p>“Uncovered”: <span class="math inline">\(E^e\)</span> adalah ekspektasi, bukan kurs yang dikunci kontrak. Investor menanggung risiko FX.</p></li>
<li><p>Jika UIP gagal → ada expected profit sistematis → ada risk premium (KOM abstraksikan).</p></li>
</ul>
</section>
<section id="uip-diagram" class="slide level2 m">
<h2>UIP diagram</h2>
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li><p>Horizontal: expected return (dalam Rp).</p></li>
<li><p>Vertical: <span class="math inline">\(E\)</span> (Rp/USD).</p></li>
<li><p>IDR return: vertikal di <span class="math inline">\(R\)</span> (tidak tergantung <span class="math inline">\(E\)</span>).</p></li>
<li><p>USD return: downward sloping — semakin <span class="math inline">\(E\)</span> tinggi, semakin kecil expected depreciation.</p></li>
<li><p>Equilibrium <span class="math inline">\(E^*\)</span>: perpotongan dua kurva.</p></li>
</ul>
<p>Tiga goncangan: <span class="math inline">\(R \uparrow\)</span>, <span class="math inline">\(R^* \uparrow\)</span>, <span class="math inline">\(E^e \uparrow\)</span>.</p>
</div><div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-2-1.png" width="480"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="effect-of-bi-rate-hike" class="slide level2 s">
<h2>Effect of BI rate hike</h2>
<ul>
<li><p>BI menaikkan <span class="math inline">\(R\)</span> dari 5,75% → 6,25%.</p></li>
<li><p>Diagram UIP: garis vertikal IDR return bergeser <em>ke kanan</em>; USD return tidak bergerak.</p></li>
<li><p>Equilibrium baru: <span class="math inline">\(E\)</span> turun → <strong>rupiah apresiasi</strong>.</p></li>
<li><p>Intuisi: bunga rupiah lebih tinggi → demand IDR deposit naik → IDR menguat.</p></li>
<li><p>Efek <em>instan</em> pada FX, bukan via jalur kredit.</p></li>
</ul>
</section>
<section id="fed-rate-hike-2013-taper-tantrum" class="slide level2 s">
<h2>Fed rate hike (2013 taper tantrum)</h2>
<ul>
<li><p>Fed naikkan <span class="math inline">\(R^*\)</span> → USD return curve geser ke kanan → <span class="math inline">\(E\)</span> naik → <strong>rupiah depresiasi</strong>.</p></li>
<li><p><strong>Kasus 2013 taper tantrum</strong>:</p>
<ul>
<li><p>Mei 2013: Bernanke isyaratkan pengurangan QE.</p></li>
<li><p>Yield UST 10Y: 1,6% → 3% dalam 4 bulan.</p></li>
<li><p>USD/IDR melemah dari ~9.700 ke ~12.000 (≈ 24%) sampai akhir 2013.</p></li>
</ul></li>
<li><p>EM currencies sangat sensitif ke “monetary signal” dari Fed.</p></li>
</ul>
</section>
<section id="effect-of-expectations-2022" class="slide level2 s">
<h2>Effect of expectations (2022)</h2>
<ul>
<li><p><span class="math inline">\(E^e\)</span> naik (rupiah <em>diharapkan</em> depresiasi) → USD return geser ke kanan → <span class="math inline">\(E\)</span> naik <strong>sekarang juga</strong>.</p></li>
<li><p><strong>Self-fulfilling</strong>: ekspektasi depresiasi → depresiasi aktual.</p></li>
<li><p><strong>Kasus 2022 Fed hiking</strong>:</p>
<ul>
<li><p>Fed naikkan rate 425 bps dalam 9 bulan.</p></li>
<li><p>Flight to USD safe haven.</p></li>
<li><p>USD/IDR: 14.300 (Jan) → 15.700 (Okt 2022).</p></li>
<li><p>BI ikut hike, tapi gap tidak cukup kompensasi ekspektasi.</p></li>
</ul></li>
</ul>
</section>
<section id="forward-rates-revisited" class="slide level2 s">
<h2>Forward rates revisited</h2>
<ul>
<li><p>Forward rate <span class="math inline">\(F\)</span> = kurs yang dikunci <em>sekarang</em> untuk pengiriman masa depan.</p></li>
<li><p>Quote USD/IDR (ilustrasi):</p></li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Tenor</th>
<th>Forward</th>
<th>Premium ann.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Spot</td>
<td>16.400</td>
<td>—</td>
</tr>
<tr class="even">
<td>1m</td>
<td>16.420</td>
<td>≈ 1,5%</td>
</tr>
<tr class="odd">
<td>3m</td>
<td>16.490</td>
<td>≈ 2,2%</td>
</tr>
<tr class="even">
<td>6m</td>
<td>16.580</td>
<td>≈ 2,2%</td>
</tr>
<tr class="odd">
<td>12m</td>
<td>16.760</td>
<td>≈ 2,2%</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Premium USD/IDR hampir selalu positif (refleksi differensial bunga).</p></li>
<li><p>Berapa premium yang “fair”? → CIP (slide berikutnya).</p></li>
</ul>
</section>
<section id="forward-premium-proxy" class="slide level2">
<h2>Forward premium proxy</h2>

<img data-src="index_files/figure-revealjs/unnamed-chunk-3-1.png" width="960" class="r-stretch"></section>
<section id="hedging-pertamina-importer" class="slide level2 s">
<h2>Hedging: Pertamina importer</h2>
<ul>
<li><p>Pertamina kontrak crude 1 juta barel × USD 80 = USD 80 jt, settle 3 bulan lagi.</p></li>
<li><p><strong>Tanpa hedge</strong>: jika <span class="math inline">\(E\)</span> naik 16.400 → 17.000, biaya naik Rp 1,312 T → Rp 1,360 T (+Rp 48 miliar).</p></li>
<li><p><strong>Dengan forward 3m @ 16.490</strong>: lock biaya USD 80 jt × 16.490 = Rp 1,319 T. <strong>Risiko FX hilang.</strong></p></li>
<li><p>Trade-off: bayar premium ~Rp 7 miliar di atas spot — biaya “asuransi” FX.</p></li>
</ul>
</section>
<section id="carry-trade-mechanics" class="slide level2 s">
<h2>Carry trade mechanics</h2>
<ul>
<li><p><strong>Carry trade</strong> = pinjam di mata uang bunga rendah (funding currency), invest di mata uang bunga tinggi (target currency).</p></li>
<li><p>Klasik untuk IDR sebagai target currency:</p>
<ol type="1">
<li><p>Pinjam USD @ 4,5% (Fed Funds + sedikit spread).</p></li>
<li><p>Convert ke IDR pada spot <span class="math inline">\(E=16.400\)</span>.</p></li>
<li><p>Beli SBN 10Y dengan yield ≈ 6,5%.</p></li>
<li><p>Setelah 1 tahun, jual SBN, convert balik ke USD, lunasi pinjaman.</p></li>
</ol></li>
<li><p>Return ekspektasi (per UIP) = <span class="math inline">\(R - R^* - \frac{E^e-E}{E} = 6{,}5 - 4{,}5 - 2{,}44 = -0{,}44\%\)</span> (jika ekspektasi sesuai forward).</p></li>
<li><p>Tapi banyak trader bertaruh bahwa <strong>realisasi depresiasi &lt; ekspektasi forward</strong> → ada profit ex-post.</p></li>
</ul>
</section>
<section id="when-carry-blows-up" class="slide level2 s">
<h2>When carry blows up</h2>
<ul>
<li><p>Saat <span class="math inline">\(E\)</span> stabil / rupiah apresiasi: spread positif = keuntungan murni.</p></li>
<li><p>Saat rupiah <em>suddenly depreciate</em>: keuntungan kumulatif bisa hilang dalam hitungan hari.</p></li>
<li><p>Episode tipikal:</p>
<ul>
<li><p><strong>2013 taper tantrum</strong>: IDR depresiasi 24% dalam ~4 bulan.</p></li>
<li><p><strong>Maret 2020 (COVID)</strong>: IDR ke 16.500 dalam beberapa minggu.</p></li>
<li><p><strong>2022 Fed hiking</strong>: IDR depresiasi ~10% dalam setahun.</p></li>
</ul></li>
<li><p>Karakteristik klasik: “picking up nickels in front of a steamroller.”</p></li>
</ul>
</section>
<section id="ex-post-carry-pl" class="slide level2">
<h2>Ex-post carry P&amp;L</h2>

<img data-src="index_files/figure-revealjs/unnamed-chunk-4-1.png" width="960" class="r-stretch"></section>
<section id="cip-derivation" class="slide level2 s">
<h2>CIP derivation</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Covered Interest Parity</strong>:</p>
<p><span class="math display">\[
R = R^* + \frac{F - E}{E}
\]</span></p>
<p>Equivalen:</p>
<p><span class="math display">\[
\frac{F}{E} = \frac{1+R}{1+R^*}
\]</span></p>
<p>Forward premium = differensial bunga; jika tidak → arbitrase.</p>
</div><div class="column" style="width:50%;">
<p><strong>Arbitrase</strong> jika <span class="math inline">\(F\)</span> terlalu tinggi:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Step</th>
<th>Cashflow</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Borrow USD 1 @ <span class="math inline">\(R^*\)</span></td>
<td><span class="math inline">\(+1\)</span> USD</td>
</tr>
<tr class="even">
<td>Convert ke Rp</td>
<td><span class="math inline">\(+E\)</span> Rp</td>
</tr>
<tr class="odd">
<td>Deposit Rp @ <span class="math inline">\(R\)</span></td>
<td><span class="math inline">\(E(1+R)\)</span> Rp</td>
</tr>
<tr class="even">
<td>Sell forward <span class="math inline">\(F\)</span></td>
<td><span class="math inline">\(E(1+R)/F\)</span> USD</td>
</tr>
<tr class="odd">
<td>Repay USD loan</td>
<td><span class="math inline">\(-(1+R^*)\)</span></td>
</tr>
<tr class="even">
<td>Profit</td>
<td><span class="math inline">\(E(1+R)/F - (1+R^*)\)</span></td>
</tr>
</tbody>
</table>
<p>Positif jika <span class="math inline">\(F &lt; E(1+R)/(1+R^*)\)</span>.</p>
</div></div>
</section>
<section id="cip-vs-uip-forward-bias" class="slide level2 s">
<h2>CIP vs UIP, forward bias</h2>
<ul>
<li><p><strong>CIP</strong> holds karena <em>arbitrage</em> — tidak butuh asumsi ekspektasi. Jika gagal, ada free money.</p></li>
<li><p><strong>UIP</strong> butuh asumsi rasional &amp; risk-neutral expectations. Empiris: sering gagal.</p></li>
<li><p><strong>Forward as predictor</strong>: secara statistik, <span class="math inline">\(F\)</span> adalah <em>biased and noisy</em> predictor untuk <span class="math inline">\(E^e\)</span>.</p>
<ul>
<li><p>Forward premium puzzle: currency dengan high interest rate justru cenderung <strong>appreciate</strong>, bukan depreciate (kebalikan UIP).</p></li>
<li><p>Implikasi: carry trade rata-rata profitable secara ex-post (dengan risiko crash).</p></li>
</ul></li>
</ul>
</section>
<section id="cip-breakdown-2008" class="slide level2 s">
<h2>CIP breakdown 2008</h2>
<ul>
<li><p>2007-08 Global Financial Crisis: CIP yang “selalu holds” tiba-tiba gagal.</p></li>
<li><p>Apa yang terjadi?</p>
<ul>
<li><p>Bank-bank tidak mau lend USD ke counterparty Eropa karena khawatir solvensi.</p></li>
<li><p>Akses ke USD funding terbatas → bank Eropa harus pay premium untuk USD via swap → <span class="math inline">\(F\)</span> deviates dari teori CIP.</p></li>
</ul></li>
<li><p>Pelajaran:</p>
<ul>
<li><p>CIP holds <strong>only when</strong> ada pasar funding yang lancar.</p></li>
<li><p>“No arbitrage” mengasumsikan akses kredit yang bebas — asumsi yang gagal saat krisis.</p></li>
</ul></li>
<li><p>Post-2008: CIP basis (cross-currency basis) tetap non-zero untuk banyak pasangan, refleksi regulasi &amp; balance sheet costs perbankan.</p></li>
</ul>
</section>
<section id="what-is-money" class="slide level2 s">
<h2>What is money?</h2>
<ul>
<li><p><strong>Money</strong> = aset yang diterima luas sebagai pembayaran.</p></li>
<li><p>Klasifikasi BI (=IMF standard):</p>
<ul>
<li><p><strong>M1</strong> (narrow) = uang kartal + giro/demand deposits.</p></li>
<li><p><strong>M2</strong> (broad) = M1 + savings + small time deposits + e-money + uang kuasi.</p></li>
<li><p><strong>M3</strong> = M2 + securities lainnya.</p></li>
</ul></li>
<li><p>Per April 2026 (ilustrasi): M1 ≈ Rp 5.000 T, M2 ≈ Rp 9.500 T.</p></li>
<li><p>BI publish bulanan di SEKI. Yang penting: <strong>kontrol BI atas supply</strong>, bukan kuantitasnya.</p></li>
</ul>
</section>
<section id="functions-of-money" class="slide level2 s">
<h2>Functions of money</h2>
<ul>
<li><p><strong>Medium of exchange</strong>: alat tukar — menggantikan barter, mengurangi cost dari “double coincidence of wants”.</p></li>
<li><p><strong>Unit of account</strong>: ukuran nilai. Kita pricing dalam Rupiah, bukan dalam beras atau emas.</p></li>
<li><p><strong>Store of value</strong>: cara menyimpan daya beli antar waktu. Tabung sekarang, konsumsi nanti.</p></li>
<li><p>Pertanyaan: mengapa transaksi domestik Indonesia pakai Rupiah, bukan USD?</p>
<ul>
<li><p>Konvensi &amp; UU mata uang (UU No.&nbsp;7/2011).</p></li>
<li><p>Network externality: makin banyak yang pakai, makin berguna sebagai MoE.</p></li>
<li><p>Tapi fungsi store of value Rupiah bisa <em>terbongkar</em> jika inflasi tidak terkendali — kasus berikutnya.</p></li>
</ul></li>
</ul>
</section>
<section id="case-study-indonesia-1963-66-hyperinflation" class="slide level2 m">
<h2>Case study: Indonesia 1963-66 hyperinflation</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Kronologi</strong>:</p>
<ul>
<li><p>1959-65: defisit APBN meledak (proyek Nasakom, konfrontasi Malaysia), didanai pencetakan uang via BI.</p></li>
<li><p>1965: <em>Sanering</em> — re-denominasi Rp 1.000 → Rp 1, untuk “menarik” supply uang.</p></li>
<li><p>1966: inflasi tahunan ≈ 636% (estimasi BPS/BI historis).</p></li>
<li><p>Setelah Orde Baru (1967+): IMF stabilisasi, fiscal tightening, inflasi turun ke ~10% pada 1969.</p></li>
</ul>
<p><strong>Mengapa relevan untuk FX</strong>:</p>
<ul>
<li><p>Money supply ↑↑ → P ↑↑ → IDR collapse vs USD.</p></li>
<li><p>Functions of money rusak: penduduk lari ke USD, emas, atau barter.</p></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-5-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="money-supply-control" class="slide level2 s">
<h2>Money supply control</h2>
<ul>
<li><p>BI sebagai otoritas moneter. Tools utama:</p>
<ul>
<li><p><strong>OMO</strong>: beli/jual SBI/SBN untuk inject/absorb likuiditas (reverse repo harian).</p></li>
<li><p><strong>Reserve requirement (GWM)</strong>: cadangan minimum bank di BI (≈ 9%).</p></li>
<li><p><strong>BI 7DRR</strong>: policy rate sejak 2016, signal ke pasar interbank.</p></li>
<li><p><strong>Standing facilities</strong>: deposit &amp; lending facility = koridor di sekitar 7DRR.</p></li>
</ul></li>
<li><p>Short-run: BI <em>sets</em> <span class="math inline">\(R\)</span> (bukan <span class="math inline">\(M\)</span>). Demand uang menentukan <span class="math inline">\(M\)</span> pada <span class="math inline">\(R\)</span> tersebut.</p></li>
</ul>
</section>
<section id="what-drives-money-demand" class="slide level2 s">
<h2>What drives money demand?</h2>
<ul>
<li><p>Demand uang <span class="math inline">\(M^d\)</span> secara kualitatif:</p>
<ul>
<li><p><span class="math inline">\(\downarrow\)</span> ketika <span class="math inline">\(R\)</span> <span class="math inline">\(\uparrow\)</span>: bunga deposit lebih menarik → kurang pegang cash.</p></li>
<li><p><span class="math inline">\(\uparrow\)</span> ketika <span class="math inline">\(P\)</span> <span class="math inline">\(\uparrow\)</span>: butuh lebih banyak cash untuk transaksi yang sama dalam nominal.</p></li>
<li><p><span class="math inline">\(\uparrow\)</span> ketika <span class="math inline">\(Y\)</span> <span class="math inline">\(\uparrow\)</span>: transaksi lebih banyak → butuh lebih banyak cash.</p></li>
</ul></li>
<li><p>Model formal (KOM Ch.15): <span class="math inline">\(M^d = P \cdot L(R, Y)\)</span>.</p></li>
<li><p><strong>Itu nanti pekan depan</strong>. Hari ini cukup pakai intuisi: ketika <span class="math inline">\(R\)</span> turun, orang lebih banyak pegang cash; ketika <span class="math inline">\(R\)</span> naik, sebaliknya.</p></li>
</ul>
</section>
<section id="bridge-money-meets-fx" class="slide level2 s">
<h2>Bridge: money meets FX</h2>
<ul>
<li><p>Sejauh ini <span class="math inline">\(R\)</span> kita pakai sebagai <em>given</em> di UIP. Dari mana <span class="math inline">\(R\)</span>?</p></li>
<li><p>Versi short-run: <strong>BI set <span class="math inline">\(R\)</span></strong> melalui 7DRR.</p>
<ul>
<li><p>Money market: <span class="math inline">\(M^s = M^d(R, P, Y)\)</span>, dengan <span class="math inline">\(M^s\)</span> “controlled” lewat OMO.</p></li>
<li><p>Equilibrium: <span class="math inline">\(R\)</span> konsisten dengan target BI.</p></li>
</ul></li>
<li><p>Begitu <span class="math inline">\(R\)</span> terbentuk di money market → <em>flows</em> ke FX market via UIP.</p></li>
<li><p>Pekan depan: derivasi formal dengan model <span class="math inline">\(M^d\)</span>.</p></li>
</ul>
</section>
<section id="joint-diagram-money-market-fx" class="slide level2 m">
<h2>Joint diagram: money market + FX</h2>
<div class="columns">
<div class="column" style="width:40%;">
<p><strong>Money market (atas)</strong>:</p>
<ul>
<li><span class="math inline">\(M^s\)</span> vertikal (BI controls).</li>
<li><span class="math inline">\(M^d\)</span> downward sloping di <span class="math inline">\(R\)</span>.</li>
<li>Equilibrium <span class="math inline">\(R^*\)</span>.</li>
</ul>
<p><strong>FX market (bawah)</strong>:</p>
<ul>
<li>IDR return vertikal di <span class="math inline">\(R^*\)</span> (dari money market).</li>
<li>USD return downward sloping di <span class="math inline">\(E\)</span>.</li>
<li>Equilibrium <span class="math inline">\(E^*\)</span>.</li>
</ul>
<p><strong>Kunci</strong>: <span class="math inline">\(R^*\)</span> dari money market → garis vertikal di FX market.</p>
</div><div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-6-1.png" width="528"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="bi-cuts-rate-fx" class="slide level2 s">
<h2>BI cuts rate → FX</h2>
<ul>
<li><p>BI turunkan 7DRR 25 bps.</p></li>
<li><p>Money market: <span class="math inline">\(R\)</span> turun. FX: IDR return geser <em>ke kiri</em>; USD return tidak bergerak.</p></li>
<li><p>Equilibrium baru: <span class="math inline">\(E\)</span> naik → <strong>rupiah depresiasi</strong>.</p></li>
<li><p>Intuisi: rate cut → investor cari yield di USD → demand IDR turun.</p></li>
<li><p>Mekanisme yang membuat <em>independent monetary policy</em> ada “harga”-nya dalam floating ER.</p></li>
</ul>
</section>
<section id="fed-cuts-fx" class="slide level2 s">
<h2>Fed cuts → FX</h2>
<ul>
<li><p>Fed turunkan policy rate.</p></li>
<li><p>Foreign money market: <span class="math inline">\(R^*\)</span> turun. FX: USD return geser <em>ke kiri</em>; IDR return tidak.</p></li>
<li><p>Equilibrium baru: <span class="math inline">\(E\)</span> turun → <strong>rupiah apresiasi</strong>.</p></li>
<li><p>Simetris: dovish Fed = tailwind untuk EM currencies termasuk IDR.</p></li>
<li><p>Itu sebabnya pasar Indonesia sangat memperhatikan FOMC.</p></li>
</ul>
</section>
<section id="short-run-vs-long-run" class="slide level2 s">
<h2>Short-run vs long-run</h2>
<ul>
<li><p><strong>Short-run</strong> (yang baru saja): <span class="math inline">\(P\)</span> sticky. Yang bergerak: <span class="math inline">\(R\)</span> → <span class="math inline">\(E\)</span> → (perlahan) <span class="math inline">\(P\)</span>.</p></li>
<li><p><strong>Long-run</strong>: <span class="math inline">\(P\)</span> menyesuaikan penuh.</p>
<ul>
<li><p><span class="math inline">\(M \uparrow\)</span> → <span class="math inline">\(P \uparrow\)</span> proporsional → <span class="math inline">\(E \uparrow\)</span> proporsional (PPP).</p></li>
<li><p>“Money neutrality”: real variables tidak berubah.</p></li>
</ul></li>
<li><p>Gap antara short-run dan long-run → fenomena <em>overshooting</em>.</p></li>
</ul>
</section>
<section id="overshooting-concept" class="slide level2 s">
<h2>Overshooting concept</h2>
<ul>
<li><p>Dornbusch (1976):</p>
<ol type="1">
<li><p><span class="math inline">\(M \uparrow\)</span> langsung dalam short-run.</p></li>
<li><p><span class="math inline">\(P\)</span> sticky → <span class="math inline">\(M/P \uparrow\)</span> → <span class="math inline">\(R \downarrow\)</span>.</p></li>
<li><p>UIP butuh <span class="math inline">\((E^e-E)/E &lt; 0\)</span> → rupiah <em>diharapkan</em> apresiasi setelah jump awal.</p></li>
<li><p><span class="math inline">\(E\)</span> harus <em>melompat melewati</em> long-run level, baru perlahan apresiasi ke long-run.</p></li>
</ol></li>
<li><p><strong>Hasilnya</strong>: ER <em>overshoots</em> — gerak inisial &gt; shift fundamental.</p></li>
<li><p>Implikasi: FX volatility &gt; volatility fundamental. Fitur empiris, bukan bug.</p></li>
</ul>
</section>
<section id="overshooting-diagram" class="slide level2">
<h2>Overshooting diagram</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-7-1.png" width="528"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<ul>
<li><p><span class="math inline">\(t&lt;0\)</span>: equilibrium di <span class="math inline">\(E_0\)</span>.</p></li>
<li><p><span class="math inline">\(t=0\)</span>: BI ekspansi moneter permanen → <span class="math inline">\(E\)</span> jump naik <strong>melebihi</strong> long-run.</p></li>
<li><p><span class="math inline">\(t&gt;0\)</span>: <span class="math inline">\(E\)</span> perlahan apresiasi ke long-run baru (di atas <span class="math inline">\(E_0\)</span>).</p></li>
<li><p>Magnitude overshoot tergantung <em>stickiness</em> harga.</p></li>
</ul>
</div></div>
</section>
<section id="takeaways" class="slide level2 s">
<h2>Takeaways</h2>
<ul>
<li><p>Nilai tukar adalah <strong>harga aset</strong>, ditentukan oleh expected return.</p></li>
<li><p><strong>UIP</strong>: equilibrium antara <span class="math inline">\(R\)</span>, <span class="math inline">\(R^*\)</span>, <span class="math inline">\(E\)</span>, <span class="math inline">\(E^e\)</span>.</p></li>
<li><p><strong>CIP</strong> berlaku karena arbitrase. UIP sering gagal → carry trade exist.</p></li>
<li><p>Forward &amp; options = tools untuk <em>hedge</em> (Pertamina) atau <em>bet</em> (carry trader).</p></li>
<li><p>BI set <span class="math inline">\(R\)</span> via 7DRR → langsung berimplikasi ke <span class="math inline">\(E\)</span> via UIP.</p></li>
<li><p>Short-run: <span class="math inline">\(P\)</span> sticky → ER bisa <strong>overshoot</strong> fundamental.</p></li>
</ul>
</section>
<section id="practice-1-uip-calculation" class="slide level2 s">
<h2>Practice 1: UIP calculation</h2>
<ul>
<li><p>Diketahui: <span class="math inline">\(R = 6{,}00\%\)</span>, <span class="math inline">\(R^* = 4{,}25\%\)</span>, <span class="math inline">\(E = 16.400\)</span>. UIP holds.</p></li>
<li><p>Berapa <span class="math inline">\(E^e\)</span> (1 tahun ke depan)?</p></li>
</ul>
<div class="fragment">
<p><strong>Solusi</strong>:</p>
<p><span class="math display">\[
\frac{E^e - E}{E} = R - R^* = 1{,}75\%
\]</span></p>
<p><span class="math display">\[
E^e = 16.400 \times 1{,}0175 \approx 16.687
\]</span></p>
<p>Pasar mengekspektasikan rupiah depresiasi ringan ke ≈ Rp 16.687/USD.</p>
</div>
</section>
<section id="practice-2-carry-trade-pl" class="slide level2 s">
<h2>Practice 2: Carry trade P&amp;L</h2>
<ul>
<li><p>Trader pinjam USD 1 jt @ 4,5% selama 1 tahun. Convert ke IDR pada <span class="math inline">\(E=16.400\)</span> → Rp 16,4 mlr. Invest di SBN @ 6,5% → Rp 17,466 mlr.</p></li>
<li><p><strong>Skenario A</strong> (<span class="math inline">\(E\)</span> stabil 16.400): convert balik = USD 1,065 jt. Lunasi 1,045 jt → <strong>profit USD 20.000</strong>.</p></li>
<li><p><strong>Skenario B</strong> (<span class="math inline">\(E\)</span> ke 17.000, depresiasi 3,7%): convert balik = USD 1,027 jt → <strong>loss USD 18.000</strong>.</p></li>
<li><p>Pelajaran: carry <em>bertaruh</em> rupiah tidak depresiasi melebihi differensial bunga (~2%).</p></li>
</ul>
</section>
<section id="practice-3-cip-arbitrage" class="slide level2 s">
<h2>Practice 3: CIP arbitrage</h2>
<ul>
<li><p>Diketahui: <span class="math inline">\(R = 6{,}00\%\)</span>, <span class="math inline">\(R^* = 4{,}25\%\)</span>, <span class="math inline">\(E = 16.400\)</span>, <span class="math inline">\(F = 16.900\)</span> (1Y).</p></li>
<li><p>Apakah ada arbitrase?</p></li>
</ul>
<div class="fragment">
<p><strong>Solusi</strong>: CIP fair forward:</p>
<p><span class="math display">\[
F^* = E \cdot \frac{1+R}{1+R^*} = 16.400 \cdot \frac{1{,}06}{1{,}0425} \approx 16.675
\]</span></p>
<p><span class="math inline">\(F = 16.900 &gt; F^* = 16.675\)</span>. Strategi: borrow USD, swap to Rp, deposit Rp, sell forward 1Y. Profit ≈ 1,37% per USD borrowed.</p>

</div>
</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="index_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="index_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="index_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="index_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="index_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="index_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="index_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'convex',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>